/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        pk: {
          primary: 'var(--pk-primary)',
          'primary-bright': 'var(--pk-primary-bright)',
          'primary-interactive': 'var(--pk-primary-interactive)',
          'primary-accent': 'var(--pk-primary-accent)',
          navy: 'var(--pk-navy)',
          dark: 'var(--pk-dark)',
          'blue-soft': 'var(--pk-blue-soft)',
          'blue-light': 'var(--pk-blue-light)',
          background: 'var(--pk-background)',
          surface: 'var(--pk-surface)',
        },
        primary: {
          DEFAULT: 'var(--pk-primary)',
          foreground: '#ffffff',
        },
        background: '#ffffff',
        foreground: '#0f172a',
        brand: {
          50: '#eff5fb',
          100: '#d9e7fd',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#1d8cf6',
          500: '#0198fd',
          600: '#0158fc',
          700: '#0062fd',
          800: '#063585',
          900: '#0b1f44',
          950: '#06132b',
        },
        indigo: {
          50: '#eff5fb',
          100: '#d9e7fd',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#1d8cf6',
          500: '#0198fd',
          600: '#0158fc',
          700: '#0062fd',
          800: '#063585',
          900: '#0b1f44',
          950: '#06132b',
        },
        slate: {
          850: '#151f32',
          950: '#090d16',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Noto Sans Bengali',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [],
};
