import {
  Exam,
  Subject,
  Chapter,
  MockTest,
  Question,
  TestAttempt,
  SubscriptionPlan,
  UserProfile,
  MistakeItem,
  BookmarkItem,
} from '@/types';

export const MOCK_STUDENT_USER: UserProfile = {
  id: 'usr-student-001',
  fullName: 'Subhamoy Banerjee',
  email: 'student@practicekoro.com',
  phone: '+91 98765 43210',
  avatarUrl:
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  targetExamId: 'wbp-constable',
  role: 'student',
  createdAt: '2025-01-10T10:00:00Z',
};

export const MOCK_ADMIN_USER: UserProfile = {
  id: 'usr-admin-001',
  fullName: 'Admin PracticeKoro',
  email: 'admin@practicekoro.com',
  phone: '+91 98300 12345',
  avatarUrl:
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  role: 'admin',
  createdAt: '2024-12-01T10:00:00Z',
};

export const MOCK_EXAMS: Exam[] = [
  {
    id: 'wbp-constable',
    title: 'WBP Constable',
    slug: 'wbp-constable',
    description: 'West Bengal Police Constable Prelims & Mains Exam Mock Tests & Practice.',
    category: 'West Bengal Police',
    iconName: 'Shield',
    orderIndex: 1,
    isActive: true,
  },
  {
    id: 'kp-police-si',
    title: 'Kolkata Police SI',
    slug: 'kolkata-police-si',
    description: 'Kolkata Police Sub-Inspector & Sergeant Recruitment Examination.',
    category: 'West Bengal Police',
    iconName: 'Award',
    orderIndex: 2,
    isActive: true,
  },
  {
    id: 'wbcs-prelims',
    title: 'WBCS Executive Prelims',
    slug: 'wbcs-prelims',
    description: 'West Bengal Civil Service (Executive) Preliminary 200 Marks Mock Series.',
    category: 'State Civil Services',
    iconName: 'FileCheck',
    orderIndex: 3,
    isActive: true,
  },
  {
    id: 'wbpsc-clerkship',
    title: 'WBPSC Clerkship',
    slug: 'wbpsc-clerkship',
    description: 'WBPSC Lower Division Clerk Part-I Comprehensive Mock Tests.',
    category: 'State Govt.',
    iconName: 'GraduationCap',
    orderIndex: 4,
    isActive: true,
  },
];

export const MOCK_SUBJECTS: Record<string, Subject[]> = {
  universal: [
    {
      id: 'wbp-history',
      name: 'Indian History (ভারত ও বাংলার ইতিহাস)',
      slug: 'indian-history',
      description: 'Ancient, Medieval, and Modern Indian history with Bengal Renaissance.',
      iconName: 'BookOpen',
      orderIndex: 1,
      isActive: true,
      chaptersCount: 12,
    },
    {
      id: 'wbp-math',
      name: 'Elementary Mathematics (পাটিগণিত)',
      slug: 'mathematics',
      description: 'Arithmetic, percentages, profit & loss, ratio & proportion, time & work.',
      iconName: 'Calculator',
      orderIndex: 2,
      isActive: true,
      chaptersCount: 15,
    },
    {
      id: 'wbp-science',
      name: 'General Science (সাধারণ বিজ্ঞান)',
      slug: 'general-science',
      description: 'Physics, Chemistry, and Life Sciences as per secondary level syllabus.',
      iconName: 'FlaskConical',
      orderIndex: 3,
      isActive: true,
      chaptersCount: 10,
    },
    {
      id: 'wbp-polity',
      name: 'Indian Constitution (ভারতের সংবিধান ও ভূগোল)',
      slug: 'indian-constitution',
      description: 'Preamble, Fundamental Rights, Parliament, and West Bengal Geography.',
      iconName: 'Scale',
      orderIndex: 4,
      isActive: true,
      chaptersCount: 8,
    },
  ],
};

export const MOCK_CHAPTERS: Record<string, Chapter[]> = {
  'wbp-history': [
    {
      id: 'wbp-hist-indus',
      subjectId: 'wbp-history',
      name: 'Indus Valley Civilization (সিন্ধু সভ্যতা)',
      slug: 'indus-valley-civilization',
      description: 'Harappa, Mohenjodaro, urban planning, seals, trade, and culture.',
      orderIndex: 1,
      isActive: true,
    },
    {
      id: 'wbp-hist-vedic',
      subjectId: 'wbp-history',
      name: 'Vedic Period & Buddhism (বৈদিক যুগ ও বৌদ্ধ ধর্ম)',
      slug: 'vedic-period-buddhism',
      description: 'Early and Later Vedic society, literature, Jainism, Buddhism councils.',
      orderIndex: 2,
      isActive: true,
    },
    {
      id: 'wbp-hist-maurya',
      subjectId: 'wbp-history',
      name: 'Mauryan & Gupta Empire (মৌর্য ও গুপ্ত সাম্রাজ্য)',
      slug: 'maurya-gupta-empire',
      description: 'Chandragupta Maurya, Ashoka inscriptions, Samudragupta, golden age.',
      orderIndex: 3,
      isActive: true,
    },
    {
      id: 'wbp-hist-freedom',
      subjectId: 'wbp-history',
      name: 'Indian Freedom Movement (ভারতের স্বাধীনতা সংগ্রাম)',
      slug: 'freedom-movement',
      description: 'Revolt of 1857, INA, Swadeshi movement, Gandhi era, partition.',
      orderIndex: 4,
      isActive: true,
    },
  ],
};

export const MOCK_TEST_SERIES: Record<string, import('@/types').TestSeries[]> = {
  'wbp-constable': [
    {
      id: 'wbp-prelims-2025',
      examId: 'wbp-constable',
      title: 'WBP Constable 2025 Prelims Test Series',
      slug: 'wbp-prelims-2025',
      description: 'Official pattern 85-question full mocks and chapter drills.',
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      createdAt: '2026-01-01T00:00:00Z',
      examTitle: 'WBP Constable',
    },
    {
      id: 'wbp-mains-pro',
      examId: 'wbp-constable',
      title: 'WBP Constable Mains Pro Series',
      slug: 'wbp-mains-pro',
      description: 'Advanced mains test series with detailed bilingual solutions.',
      isPremium: true,
      orderIndex: 2,
      isActive: true,
      createdAt: '2026-01-01T00:00:00Z',
      examTitle: 'WBP Constable',
    },
  ],
};

export const MOCK_TESTS: Record<string, MockTest[]> = {
  'wbp-hist-indus': [
    {
      id: 'test-indus-01',
      examId: 'wbp-constable',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      testSeriesId: 'wbp-prelims-2025',
      title: 'Mock Test Part 01: Indus Valley (Free)',
      slug: 'indus-valley-mock-01',
      description: 'Essential high-yield questions on Harappa & Mohenjodaro discoveries.',
      testType: 'chapter_mock',
      durationMinutes: 15,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0.25,
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'Indian History',
      chapterName: 'Indus Valley Civilization',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
    {
      id: 'test-indus-02',
      examId: 'wbp-constable',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      testSeriesId: 'wbp-prelims-2025',
      title: 'Mock Test Part 02: High-Yield Indus (Premium)',
      slug: 'indus-valley-mock-02',
      description: 'Advanced questions on archaeological sites, seals, religion and trade.',
      testType: 'chapter_mock',
      durationMinutes: 20,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0.25,
      isPremium: true,
      orderIndex: 2,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'Indian History',
      chapterName: 'Indus Valley Civilization',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
    {
      id: 'test-indus-03',
      examId: 'wbp-constable',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      testSeriesId: 'wbp-prelims-2025',
      title: 'Mock Test Part 03: PYQ Mastery (Premium)',
      slug: 'indus-valley-mock-03',
      description: 'Past 10 years WBPRB and WBPSC exam question compilation with explanations.',
      testType: 'chapter_mock',
      durationMinutes: 20,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0.25,
      isPremium: true,
      orderIndex: 3,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'Indian History',
      chapterName: 'Indus Valley Civilization',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
  ],
};

export const MOCK_QUESTIONS: Record<string, Question[]> = {
  'test-indus-01': [
    {
      id: 'q-indus-01',
      chapterId: 'wbp-hist-indus',
      questionText: 'Who discovered the archaeological ruins of Harappa in 1921?',
      questionBengaliText: '১৯২১ সালে হরপ্পা প্রত্নক্ষেত্রটি কে আবিষ্কার করেছিলেন?',
      optionA: 'Rakhal Das Banerjee',
      optionB: 'Daya Ram Sahni',
      optionC: 'Sir John Marshall',
      optionD: 'Alexander Cunningham',
      correctOption: 'B',
      explanation:
        'Daya Ram Sahni excavated Harappa in Montgomery district (now in Sahiwal, Pakistan) in 1921 under Sir John Marshall.',
      explanationBengali:
        '১৯২১ সালে প্রত্নতাত্ত্বিক দয়ারাম সাহনি হরপ্পা সভ্যতা আবিষ্কার ও খননকাজ পরিচালনা করেন।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      isActive: true,
    },
    {
      id: 'q-indus-02',
      chapterId: 'wbp-hist-indus',
      questionText: 'The Great Bath of the Indus Valley Civilization was discovered at which site?',
      questionBengaliText: 'সিন্ধু সভ্যতার বিখ্যাত স্নানাগারটি (Great Bath) কোথায় পাওয়া গেছে?',
      optionA: 'Harappa',
      optionB: 'Lothal',
      optionC: 'Mohenjodaro',
      optionD: 'Kalibangan',
      correctOption: 'C',
      explanation:
        'The Great Bath was discovered in Mohenjodaro, built with burnt bricks and coated with natural bitumen/pitch.',
      explanationBengali:
        'বিখ্যাত স্নানাগারটি মহেঞ্জোদারোতে অবস্থিত, যা পোড়ামাটির ইট ও বিটুমিন দিয়ে জলনিরোধক করা হয়েছিল।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      isActive: true,
    },
    {
      id: 'q-indus-03',
      chapterId: 'wbp-hist-indus',
      questionText: 'Which Indus Valley city is famous for having an artificial tidal dockyard?',
      questionBengaliText: 'সিন্ধু সভ্যতার কোন শহরটিতে প্রাচীন কৃত্রিম পোতাশ্রয় বা ডকইয়ার্ড ছিল?',
      optionA: 'Lothal',
      optionB: 'Surkotada',
      optionC: 'Banawali',
      optionD: 'Rakhigarhi',
      correctOption: 'A',
      explanation:
        'Lothal in Gujarat had a tidal dockyard connected to the Sabarmati river basin for overseas maritime trade.',
      explanationBengali:
        'গুজরাটের লোথালে বিশ্বের অন্যতম প্রাচীন কৃত্রিম নৌ-ঘাঁটি বা বন্দর আবিষ্কৃত হয়েছে।',
      difficulty: 'medium',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      isActive: true,
    },
    {
      id: 'q-indus-04',
      chapterId: 'wbp-hist-indus',
      questionText: 'The Indus Valley Civilization belonged to which historical age?',
      questionBengaliText: 'সিন্ধু সভ্যতা কোন ঐতিহাসিক যুগের অন্তর্গত ছিল?',
      optionA: 'Paleolithic Age',
      optionB: 'Mesolithic Age',
      optionC: 'Chalcolithic / Bronze Age',
      optionD: 'Iron Age',
      correctOption: 'C',
      explanation:
        'The Indus Valley Civilization belonged to the Bronze Age (Proto-historic period). Harappans did not know the use of iron.',
      explanationBengali:
        'সিন্ধু সভ্যতা ব্রোঞ্জ বা তাম্র-ব্রোঞ্জ যুগের সভ্যতা ছিল। লোহার ব্যবহার তাদের অজানা ছিল।',
      difficulty: 'medium',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      isActive: true,
    },
    {
      id: 'q-indus-05',
      chapterId: 'wbp-hist-indus',
      questionText: 'Which Indus Valley site has yielded clear evidence of a ploughed field?',
      questionBengaliText: 'সিন্ধু সভ্যতার কোন কেন্দ্রে লাঙল দেওয়া চাষের জমির প্রমাণ পাওয়া গেছে?',
      optionA: 'Chanhudaro',
      optionB: 'Kalibangan',
      optionC: 'Dholavira',
      optionD: 'Kot Diji',
      correctOption: 'B',
      explanation:
        'Kalibangan in Rajasthan shows evidence of furrows intersecting at right angles, showing double cropping in a ploughed field.',
      explanationBengali: 'রাজস্থানের কালিবঙ্গানে লাঙল চষা কৃষি ক্ষেত্রের নিদর্শন আবিষ্কৃত হয়েছে।',
      difficulty: 'hard',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      isActive: true,
    },
  ],
};

export const MOCK_ATTEMPTS: TestAttempt[] = [
  {
    id: 'att-001',
    userId: 'usr-student-001',
    testId: 'test-indus-01',
    testTitle: 'Mock Test Part 01: Indus Valley (Free)',
    status: 'completed',
    startTime: '2025-02-10T14:00:00Z',
    endTime: '2025-02-10T14:11:30Z',
    timeSpentSeconds: 690,
    score: 4.75,
    totalMarks: 5.0,
    correctCount: 4,
    wrongCount: 1,
    skippedCount: 0,
    accuracy: 80.0,
    rank: 14,
    percentile: 94.5,
    createdAt: '2025-02-10T14:12:00Z',
  },
];

export const MOCK_MISTAKES: MistakeItem[] = [
  {
    id: 'mst-001',
    userId: 'usr-student-001',
    questionId: 'q-indus-05',
    question: MOCK_QUESTIONS['test-indus-01'][4],
    wrongCount: 2,
    isResolved: false,
    lastReviewedAt: '2025-02-10T14:15:00Z',
    createdAt: '2025-02-10T14:12:00Z',
  },
];

export const MOCK_BOOKMARKS: BookmarkItem[] = [
  {
    id: 'bm-001',
    userId: 'usr-student-001',
    questionId: 'q-indus-03',
    question: MOCK_QUESTIONS['test-indus-01'][2],
    note: 'Important dockyard question repeatedly asked in WBP 2021 & 2024 exams.',
    createdAt: '2025-02-10T14:13:00Z',
  },
];

export const MOCK_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'pro_1_year',
    title: '1-Year All-Access Pass',
    description:
      'Unlimited access to ALL Premium Mock Tests across all West Bengal exams for 365 days.',
    durationDays: 365,
    price: 299,
    originalPrice: 999,
    currency: 'INR',
    features: [
      'Unlock ALL Premium Mock Tests across all exams',
      'WBP Constable, KP SI, WBCS & WBPSC Clerkship',
      'Automatic Mistakes Notebook & Smart Revision',
      'Detailed Step-by-Step Explanations (Bengali & English)',
      'State-Level Rank & Percentile Analytics',
      'Validity: Full 365 Days',
    ],
    isActive: true,
    orderIndex: 1,
  },
  {
    id: 'pro_6_month',
    title: '6-Month Exam Pass',
    description: 'Complete access to all premium tests for 180 days.',
    durationDays: 180,
    price: 199,
    originalPrice: 599,
    currency: 'INR',
    features: [
      'Unlock ALL Premium Mock Tests',
      'Detailed Explanations & Solutions',
      'Mistakes Notebook & Bookmarks',
      'Validity: 180 Days',
    ],
    isActive: true,
    orderIndex: 2,
  },
];
