import {
  Exam,
  Subject,
  Chapter,
  MockTest,
  Question,
  TestAttempt,
  SubscriptionPlan,
  UserProfile,
  MistakeItem,
  BookmarkItem,
} from '@/types';

export const MOCK_STUDENT_USER: UserProfile = {
  id: 'usr-student-001',
  fullName: 'Subhamoy Banerjee',
  email: 'student@practicekoro.com',
  phone: '+91 98765 43210',
  avatarUrl:
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  targetExamId: 'wbp-constable',
  role: 'student',
  createdAt: '2025-01-10T10:00:00Z',
};

export const MOCK_ADMIN_USER: UserProfile = {
  id: 'usr-admin-001',
  fullName: 'Admin PracticeKoro',
  email: 'admin@practicekoro.com',
  phone: '+91 98300 12345',
  avatarUrl:
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  role: 'admin',
  createdAt: '2024-12-01T10:00:00Z',
};

export const MOCK_EXAMS: Exam[] = [
  {
    id: 'wbp-constable',
    title: 'WBP Constable',
    slug: 'wbp-constable',
    description: 'West Bengal Police Constable Prelims & Mains Exam Mock Tests & Practice.',
    category: 'West Bengal Police',
    iconName: 'Shield',
    orderIndex: 1,
    isActive: true,
  },
  {
    id: 'kp-police-si',
    title: 'Kolkata Police SI',
    slug: 'kolkata-police-si',
    description: 'Kolkata Police Sub-Inspector & Sergeant Recruitment Examination.',
    category: 'West Bengal Police',
    iconName: 'Award',
    orderIndex: 2,
    isActive: true,
  },
  {
    id: 'wbcs-prelims',
    title: 'WBCS Executive Prelims',
    slug: 'wbcs-prelims',
    description: 'West Bengal Civil Service (Executive) Preliminary 200 Marks Mock Series.',
    category: 'State Civil Services',
    iconName: 'FileCheck',
    orderIndex: 3,
    isActive: true,
  },
  {
    id: 'wbpsc-clerkship',
    title: 'WBPSC Clerkship',
    slug: 'wbpsc-clerkship',
    description: 'WBPSC Lower Division Clerk Part-I Comprehensive Mock Tests.',
    category: 'State Govt.',
    iconName: 'GraduationCap',
    orderIndex: 4,
    isActive: true,
  },
];

export const MOCK_SUBJECTS: Record<string, Subject[]> = {
  universal: [
    {
      id: 'wbp-history',
      name: 'Indian History (ভারত ও বাংলার ইতিহাস)',
      slug: 'indian-history',
      description: 'Ancient, Medieval, and Modern Indian history with Bengal Renaissance.',
      iconName: 'BookOpen',
      orderIndex: 1,
      isActive: true,
      chaptersCount: 12,
    },
    {
      id: 'wbp-math',
      name: 'Elementary Mathematics (পাটিগণিত)',
      slug: 'mathematics',
      description: 'Arithmetic, percentages, profit & loss, ratio & proportion, time & work.',
      iconName: 'Calculator',
      orderIndex: 2,
      isActive: true,
      chaptersCount: 15,
    },
    {
      id: 'wbp-science',
      name: 'General Science (সাধারণ বিজ্ঞান)',
      slug: 'general-science',
      description: 'Physics, Chemistry, and Life Sciences as per secondary level syllabus.',
      iconName: 'FlaskConical',
      orderIndex: 3,
      isActive: true,
      chaptersCount: 10,
    },
    {
      id: 'wbp-polity',
      name: 'Indian Constitution (ভারতের সংবিধান ও ভূগোল)',
      slug: 'indian-constitution',
      description: 'Preamble, Fundamental Rights, Parliament, and West Bengal Geography.',
      iconName: 'Scale',
      orderIndex: 4,
      isActive: true,
      chaptersCount: 8,
    },
    {
      id: 'wbp-bengali',
      name: 'bengali Literature (বাংলা সাহিত্য ও ভাষা)',
      slug: 'bengali-literature',
      description: 'বাংলা সাহিত্যের ধ্রুপদী রচনা, লেখক পরিচিতি ও ব্যাকরণ।',
      iconName: 'BookOpen',
      orderIndex: 5,
      isActive: true,
      chaptersCount: 6,
    },
  ],
};

export const MOCK_CHAPTERS: Record<string, Chapter[]> = {
  'wbp-bengali': [
    {
      id: 'wbp-bengali-lit',
      subjectId: 'wbp-bengali',
      name: 'bengali Literature',
      slug: 'bengali-literature-classics',
      description: 'কাব্যগ্রন্থ, উপন্যাস, নাটক ও সাহিত্যিকদের গুরুত্বপূর্ণ তথ্য।',
      orderIndex: 1,
      isActive: true,
    },
  ],
  'wbp-history': [
    {
      id: 'wbp-hist-indus',
      subjectId: 'wbp-history',
      name: 'Indus Valley Civilization (সিন্ধু সভ্যতা)',
      slug: 'indus-valley-civilization',
      description: 'Harappa, Mohenjodaro, urban planning, seals, trade, and culture.',
      orderIndex: 1,
      isActive: true,
    },
    {
      id: 'wbp-hist-vedic',
      subjectId: 'wbp-history',
      name: 'Vedic Period & Buddhism (বৈদিক যুগ ও বৌদ্ধ ধর্ম)',
      slug: 'vedic-period-buddhism',
      description: 'Early and Later Vedic society, literature, Jainism, Buddhism councils.',
      orderIndex: 2,
      isActive: true,
    },
    {
      id: 'wbp-hist-maurya',
      subjectId: 'wbp-history',
      name: 'Mauryan & Gupta Empire (মৌর্য ও গুপ্ত সাম্রাজ্য)',
      slug: 'maurya-gupta-empire',
      description: 'Chandragupta Maurya, Ashoka inscriptions, Samudragupta, golden age.',
      orderIndex: 3,
      isActive: true,
    },
    {
      id: 'wbp-hist-freedom',
      subjectId: 'wbp-history',
      name: 'Indian Freedom Movement (ভারতের স্বাধীনতা সংগ্রাম)',
      slug: 'freedom-movement',
      description: 'Revolt of 1857, INA, Swadeshi movement, Gandhi era, partition.',
      orderIndex: 4,
      isActive: true,
    },
  ],
  'wbp-math': [
    {
      id: 'wbp-math-ratio',
      subjectId: 'wbp-math',
      name: 'Ratio & Proportion (অনুপাত ও সমানুপাত)',
      slug: 'ratio-and-proportion',
      description: 'অনুপাত, সমানুপাত এবং অংশীদারি কারবারের সমস্যা ও সমাধান।',
      orderIndex: 1,
      isActive: true,
    },
    {
      id: 'wbp-math-percentage',
      subjectId: 'wbp-math',
      name: 'Percentage, Profit & Loss (শতকরা ও লাভ-ক্ষতি)',
      slug: 'percentage-profit-loss',
      description: 'শতকরা হিসাব, ক্রয়মূল্য, বিক্রয়মূল্য ও ছাড় সংক্রান্ত গাণিতিক সমস্যা।',
      orderIndex: 2,
      isActive: true,
    },
    {
      id: 'wbp-math-time',
      subjectId: 'wbp-math',
      name: 'Time & Work (সময় ও কার্য)',
      slug: 'time-and-work',
      description: 'সময় ও কার্য, নল ও চৌবাচ্চার জটিল সমস্যা ও শর্টকাট কৌশল।',
      orderIndex: 3,
      isActive: true,
    },
  ],
  'wbp-science': [
    {
      id: 'wbp-sci-physics',
      subjectId: 'wbp-science',
      name: 'General Physics (পদার্থবিদ্যা ও বলবিজ্ঞান)',
      slug: 'general-physics',
      description: 'গতি, বল, কার্য, শক্তি ও ক্ষমতার মৌলিক নীতি ও প্রয়োগ।',
      orderIndex: 1,
      isActive: true,
    },
    {
      id: 'wbp-sci-life',
      subjectId: 'wbp-science',
      name: 'Life Science & Physiology (জীববিদ্যা ও মানবদেহ)',
      slug: 'life-science-human-body',
      description: 'কোষ, কলা, পরিপাকতন্ত্র, রক্ত সংবহন ও ভিটামিন বিষয়ক তথ্যাদি।',
      orderIndex: 2,
      isActive: true,
    },
  ],
  'wbp-polity': [
    {
      id: 'wbp-pol-rights',
      subjectId: 'wbp-polity',
      name: 'Fundamental Rights & DPSP (মৌলিক অধিকার ও নির্দেশক নীতি)',
      slug: 'fundamental-rights-dpsp',
      description: 'সংবিধানের তৃতীয় ও চতুর্থ ভাগ: মৌলিক অধিকার, কর্তব্য ও অনুচ্ছেদসমূহ।',
      orderIndex: 1,
      isActive: true,
    },
    {
      id: 'wbp-pol-preamble',
      subjectId: 'wbp-polity',
      name: 'Preamble & Parliament (প্রস্তাবনা ও ভারতীয় সংসদ)',
      slug: 'preamble-and-parliament',
      description: 'সংবিধানের প্রস্তাবনা, রাষ্ট্রপতি, লোকসভা ও রাজ্যসভার কার্যাবলী।',
      orderIndex: 2,
      isActive: true,
    },
  ],
};

export const MOCK_TEST_SERIES: Record<string, import('@/types').TestSeries[]> = {
  'wbp-constable': [
    {
      id: 'wbp-prelims-2025',
      examId: 'wbp-constable',
      title: 'WBP Constable 2025 Prelims Test Series',
      slug: 'wbp-prelims-2025',
      description: 'Official pattern 85-question full mocks and chapter drills.',
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      createdAt: '2026-01-01T00:00:00Z',
      examTitle: 'WBP Constable',
    },
    {
      id: 'wbp-mains-pro',
      examId: 'wbp-constable',
      title: 'WBP Constable Mains Pro Series',
      slug: 'wbp-mains-pro',
      description: 'Advanced mains test series with detailed bilingual solutions.',
      isPremium: true,
      orderIndex: 2,
      isActive: true,
      createdAt: '2026-01-01T00:00:00Z',
      examTitle: 'WBP Constable',
    },
  ],
};

export const MOCK_TESTS: Record<string, MockTest[]> = {
  'wbp-hist-indus': [
    {
      id: 'test-indus-01',
      examId: 'wbp-constable',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      testSeriesId: 'wbp-prelims-2025',
      title: 'Mock Test Part 01: Indus Valley (Free)',
      slug: 'indus-valley-mock-01',
      description: 'Essential high-yield questions on Harappa & Mohenjodaro discoveries.',
      testType: 'chapter_mock',
      durationMinutes: 15,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0.25,
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'Indian History',
      chapterName: 'Indus Valley Civilization',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
    {
      id: 'test-indus-02',
      examId: 'wbp-constable',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      testSeriesId: 'wbp-prelims-2025',
      title: 'Mock Test Part 02: High-Yield Indus (Premium)',
      slug: 'indus-valley-mock-02',
      description: 'Advanced questions on archaeological sites, seals, religion and trade.',
      testType: 'chapter_mock',
      durationMinutes: 20,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0.25,
      isPremium: true,
      orderIndex: 2,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'Indian History',
      chapterName: 'Indus Valley Civilization',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
    {
      id: 'test-indus-03',
      examId: 'wbp-constable',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      testSeriesId: 'wbp-prelims-2025',
      title: 'Mock Test Part 03: PYQ Mastery (Premium)',
      slug: 'indus-valley-mock-03',
      description: 'Past 10 years WBPRB and WBPSC exam question compilation with explanations.',
      testType: 'chapter_mock',
      durationMinutes: 20,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0.25,
      isPremium: true,
      orderIndex: 3,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'Indian History',
      chapterName: 'Indus Valley Civilization',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
  ],
  'wbp-bengali': [
    {
      id: 'test-bengali-lit-01',
      examId: 'wbp-constable',
      subjectId: 'wbp-bengali',
      chapterId: 'wbp-bengali-lit',
      testSeriesId: 'wbp-prelims-2025',
      title: 'বাংলা সাহিত্য ও বিখ্যাত রচনা (Mock 01)',
      slug: 'bengali-literature-mock-01',
      description:
        'রবীন্দ্রনাথ, বঙ্কিমচন্দ্র ও বাংলা সাহিত্যের ধ্রুপদী রচনার গুরুত্বপূর্ণ প্রশ্নাবলি।',
      testType: 'chapter_mock',
      durationMinutes: 15,
      totalQuestions: 3,
      totalMarks: 3,
      passingMarks: 1,
      negativeMarking: 0.25,
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'bengali Literature',
      chapterName: 'bengali Literature',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
  ],
  'wbp-full-mocks': [
    {
      id: 'test-wbp-mock-01',
      examId: 'wbp-constable',
      title: 'WBP Preliminary Mock Test 01',
      slug: 'wbp-preliminary-mock-test-01',
      description: 'Comprehensive Full Mock Test based on latest WBPRB syllabus and marks pattern.',
      testType: 'full_mock',
      durationMinutes: 60,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0.25,
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
    },
    {
      id: 'test-wbp-mock-02',
      examId: 'wbp-constable',
      title: 'WBP Preliminary Mock Test 02',
      slug: 'wbp-preliminary-mock-test-02',
      description:
        'Full Length preliminary mock test with updated general awareness and reasoning.',
      testType: 'full_mock',
      durationMinutes: 60,
      totalQuestions: 0,
      totalMarks: 85,
      passingMarks: 40,
      negativeMarking: 0.25,
      isPremium: true,
      orderIndex: 2,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
    },
  ],
  'wbp-pyqs': [
    {
      id: 'test-wbp-pyq-2024',
      examId: 'wbp-constable',
      title: 'WBP Preliminary Question Paper 2024',
      paperName: 'WBP Preliminary Question Paper 2024',
      slug: 'wbp-preliminary-question-paper-2024',
      description: 'Official solved question paper of WBP Preliminary Exam 2024.',
      testType: 'pyq',
      year: 2024,
      durationMinutes: 60,
      totalQuestions: 4,
      totalMarks: 4,
      passingMarks: 2,
      negativeMarking: 0.25,
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
    },
    {
      id: 'test-wbp-pyq-2023',
      examId: 'wbp-constable',
      title: 'WBP Preliminary Question Paper 2023',
      paperName: 'WBP Preliminary Question Paper 2023',
      slug: 'wbp-preliminary-question-paper-2023',
      description: 'Official solved question paper of WBP Preliminary Exam 2023.',
      testType: 'pyq',
      year: 2023,
      durationMinutes: 60,
      totalQuestions: 0,
      totalMarks: 85,
      passingMarks: 40,
      negativeMarking: 0.25,
      isPremium: false,
      orderIndex: 2,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
    },
  ],
};

export const MOCK_QUESTIONS: Record<string, Question[]> = {
  'test-bengali-lit-01': [
    {
      id: 'q-lit-01',
      subjectId: 'wbp-bengali',
      chapterId: 'wbp-bengali-lit',
      topicId: 'wbp-bengali-lit',
      questionText: "রবীন্দ্রনাথ ঠাকুরের 'গীতাঞ্জলি' কাব্যগ্রন্থটি কোন সালে প্রকাশিত হয়?",
      questionBengaliText: "রবীন্দ্রনাথ ঠাকুরের 'গীতাঞ্জলি' কাব্যগ্রন্থটি কোন সালে প্রকাশিত হয়?",
      optionA: '১৯১০',
      optionB: '১৯১২',
      optionC: '১৯১৪',
      optionD: '১৯১৬',
      correctOption: 'A',
      explanation:
        "রবীন্দ্রনাথ ঠাকুরের বিখ্যাত 'গীতাঞ্জলি' কাব্যগ্রন্থটি ১৯১০ সালে বাংলায় প্রকাশিত হয়। পরবর্তীতে এর ইংরেজি অনুবাদের (Song Offerings) জন্য তিনি ১৯১৩ সালে সাহিত্যে নোবেল পুরস্কার পান।",
      explanationBengali:
        "রবীন্দ্রনাথ ঠাকুরের বিখ্যাত 'গীতাঞ্জলি' কাব্যগ্রন্থটি ১৯১০ সালে বাংলায় প্রকাশিত হয়। পরবর্তীতে এর ইংরেজি অনুবাদের (Song Offerings) জন্য তিনি ১৯১৩ সালে সাহিত্যে নোবেল পুরস্কার পান।",
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-lit-02',
      subjectId: 'wbp-bengali',
      chapterId: 'wbp-bengali-lit',
      topicId: 'wbp-bengali-lit',
      questionText: 'বাংলা সাহিত্যের প্রথম সার্থক উপন্যাস কোনটি?',
      questionBengaliText: 'বাংলা সাহিত্যের প্রথম সার্থক উপন্যাস কোনটি?',
      optionA: 'আলালের ঘরের দুলাল',
      optionB: 'দুর্গেশনন্দিনী',
      optionC: 'কপালকুণ্ডলা',
      optionD: 'চোখের বালি',
      correctOption: 'B',
      explanation:
        "১৮৬৫ সালে প্রকাশিত সাহিত্যসম্রাট বঙ্কিমচন্দ্র চট্টোপাধ্যায়ের 'দুর্গেশনন্দিনী' উপন্যাসটিকে বাংলা সাহিত্যের প্রথম সার্থক উপন্যাস হিসেবে গণ্য করা হয়।",
      explanationBengali:
        "১৮৬৫ সালে প্রকাশিত সাহিত্যসম্রাট বঙ্কিমচন্দ্র চট্টোপাধ্যায়ের 'দুর্গেশনন্দিনী' উপন্যাসটিকে বাংলা সাহিত্যের প্রথম সার্থক উপন্যাস হিসেবে গণ্য করা হয়।",
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-lit-03',
      subjectId: 'wbp-bengali',
      chapterId: 'wbp-bengali-lit',
      topicId: 'wbp-bengali-lit',
      questionText:
        "ভারতের জাতীয় গান 'বন্দে মাতরম্' বঙ্কিমচন্দ্রের কোন উপন্যাস থেকে গৃহীত হয়েছে?",
      questionBengaliText:
        "ভারতের জাতীয় গান 'বন্দে মাতরম্' বঙ্কিমচন্দ্রের কোন উপন্যাস থেকে গৃহীত হয়েছে?",
      optionA: 'আনন্দমঠ',
      optionB: 'দেবী চৌধুরাণী',
      optionC: 'রাজসিংহ',
      optionD: 'সীতারাম',
      correctOption: 'A',
      explanation:
        "বঙ্কিমচন্দ্র চট্টোপাধ্যায়ের বিখ্যাত রাজনৈতিক ও ঐতিহাসিক উপন্যাস 'আনন্দমঠ' (১৮৮২) থেকে 'বন্দে মাতরম্' গানটি নেওয়া হয়েছে।",
      explanationBengali:
        "বঙ্কিমচন্দ্র চট্টোপাধ্যায়ের বিখ্যাত রাজনৈতিক ও ঐতিহাসিক উপন্যাস 'আনন্দমঠ' (১৮৮২) থেকে 'বন্দে মাতরম্' গানটি নেওয়া হয়েছে।",
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
  'test-indus-01': [
    {
      id: 'q-indus-01',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      topicId: 'wbp-hist-indus',
      questionText: '১৯২১ সালে হরপ্পা প্রত্নক্ষেত্রটি কে আবিষ্কার করেছিলেন?',
      questionBengaliText: '১৯২১ সালে হরপ্পা প্রত্নক্ষেত্রটি কে আবিষ্কার করেছিলেন?',
      optionA: 'রাখালদাস বন্দ্যোপাধ্যায়',
      optionB: 'দয়ারাম সাহনি',
      optionC: 'স্যার জন মার্শাল',
      optionD: 'আলেকজান্ডার কানিংহাম',
      correctOption: 'B',
      explanation:
        '১৯২১ সালে ভারতীয় প্রত্নতাত্ত্বিক দয়ারাম সাহনি স্যার জন মার্শালের তত্ত্বাবধানে হরপ্পা প্রত্নক্ষেত্রটি আবিষ্কার করেন।',
      explanationBengali:
        '১৯২১ সালে ভারতীয় প্রত্নতাত্ত্বিক দয়ারাম সাহনি স্যার জন মার্শালের তত্ত্বাবধানে হরপ্পা প্রত্নক্ষেত্রটি আবিষ্কার করেন।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-indus-02',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      topicId: 'wbp-hist-indus',
      questionText: 'সিন্ধু সভ্যতার বিখ্যাত বৃহৎ স্নানাগারটি (Great Bath) কোথায় পাওয়া গেছে?',
      questionBengaliText:
        'সিন্ধু সভ্যতার বিখ্যাত বৃহৎ স্নানাগারটি (Great Bath) কোথায় পাওয়া গেছে?',
      optionA: 'হরপ্পা',
      optionB: 'লোথাল',
      optionC: 'মহেঞ্জোদারো',
      optionD: 'কালিবঙ্গান',
      correctOption: 'C',
      explanation:
        'সিন্ধু সভ্যতার বিখ্যাত বৃহৎ স্নানাগারটি মহেঞ্জোদারোতে অবস্থিত, যা পোড়ামাটির ইট ও বিটুমিন দিয়ে জলনিরোধক করা হয়েছিল।',
      explanationBengali:
        'সিন্ধু সভ্যতার বিখ্যাত বৃহৎ স্নানাগারটি মহেঞ্জোদারোতে অবস্থিত, যা পোড়ামাটির ইট ও বিটুমিন দিয়ে জলনিরোধক করা হয়েছিল।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-indus-03',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      topicId: 'wbp-hist-indus',
      questionText: 'সিন্ধু সভ্যতার কোন শহরটিতে প্রাচীন কৃত্রিম পোতাশ্রয় বা ডকইয়ার্ড ছিল?',
      questionBengaliText: 'সিন্ধু সভ্যতার কোন শহরটিতে প্রাচীন কৃত্রিম পোতাশ্রয় বা ডকইয়ার্ড ছিল?',
      optionA: 'লোথাল',
      optionB: 'সুরকোটাদা',
      optionC: 'বনওয়ালি',
      optionD: 'রাখিগড়ী',
      correctOption: 'A',
      explanation:
        'গুজরাটের ভোগাবর নদীর তীরে অবস্থিত লোথালে বিশ্বের প্রাচীনতম কৃত্রিম সামুদ্রিক বন্দর বা ডকইয়ার্ড আবিষ্কৃত হয়েছে।',
      explanationBengali:
        'গুজরাটের ভোগাবর নদীর তীরে অবস্থিত লোথালে বিশ্বের প্রাচীনতম কৃত্রিম সামুদ্রিক বন্দর বা ডকইয়ার্ড আবিষ্কৃত হয়েছে।',
      difficulty: 'medium',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-indus-04',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      topicId: 'wbp-hist-indus',
      questionText: 'সিন্ধু সভ্যতা মূলত কোন ঐতিহাসিক যুগের অন্তর্গত ছিল?',
      questionBengaliText: 'সিন্ধু সভ্যতা মূলত কোন ঐতিহাসিক যুগের অন্তর্গত ছিল?',
      optionA: 'প্রাচীন প্রস্তর যুগ',
      optionB: 'মধ্য প্রস্তর যুগ',
      optionC: 'তাম্র-ব্রোঞ্জ যুগ',
      optionD: 'লৌহ যুগ',
      correctOption: 'C',
      explanation:
        'সিন্ধু সভ্যতা তাম্র-ব্রোঞ্জ যুগের (Bronze Age) একটি সুপরিকল্পিত নগরকেন্দ্রিক সভ্যতা ছিল। হরপ্পাবাসীদের লোহার ব্যবহার অজানা ছিল।',
      explanationBengali:
        'সিন্ধু সভ্যতা তাম্র-ব্রোঞ্জ যুগের (Bronze Age) একটি সুপরিকল্পিত নগরকেন্দ্রিক সভ্যতা ছিল। হরপ্পাবাসীদের লোহার ব্যবহার অজানা ছিল।',
      difficulty: 'medium',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-indus-05',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      topicId: 'wbp-hist-indus',
      questionText: 'সিন্ধু সভ্যতার কোন কেন্দ্রে লাঙল দেওয়া চাষের জমির প্রমাণ পাওয়া গেছে?',
      questionBengaliText: 'সিন্ধু সভ্যতার কোন কেন্দ্রে লাঙল দেওয়া চাষের জমির প্রমাণ পাওয়া গেছে?',
      optionA: 'চানহুদারো',
      optionB: 'কালিবঙ্গান',
      optionC: 'ধোলাভিরা',
      optionD: 'কোট দিজি',
      correctOption: 'B',
      explanation:
        'রাজস্থানের কালিবঙ্গানে লাঙল দিয়ে চষা কৃষিজমি ও পারস্পরিক সমকোণে থাকা খাঁজের সুস্পষ্ট প্রমাণ পাওয়া গেছে।',
      explanationBengali:
        'রাজস্থানের কালিবঙ্গানে লাঙল দিয়ে চষা কৃষিজমি ও পারস্পরিক সমকোণে থাকা খাঁজের সুস্পষ্ট প্রমাণ পাওয়া গেছে।',
      difficulty: 'hard',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
  'test-wbp-mock-01': [
    {
      id: 'q-wbp-mock-01',
      questionText: "আমাদের সৌরজগতের কোন গ্রহকে 'লাল গ্রহ' বলা হয়?",
      questionBengaliText: "আমাদের সৌরজগতের কোন গ্রহকে 'লাল গ্রহ' বলা হয়?",
      optionA: 'শুক্র',
      optionB: 'মঙ্গল',
      optionC: 'বৃহস্পতি',
      optionD: 'শনি',
      correctOption: 'B',
      explanation:
        'মঙ্গল গ্রহের পৃষ্ঠে প্রচুর পরিমাণে আয়রন অক্সাইড (মরিচা) থাকার কারণে মহাকাশ থেকে এটি লালচে দেখায়, তাই একে লাল গ্রহ বলে।',
      explanationBengali:
        'মঙ্গল গ্রহের পৃষ্ঠে প্রচুর পরিমাণে আয়রন অক্সাইড (মরিচা) থাকার কারণে মহাকাশ থেকে এটি লালচে দেখায়, তাই একে লাল গ্রহ বলে।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'other',
      sourceExam: 'wbp-constable',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-mock-02',
      questionText: 'ভারতের সংবিধানের জনক ও প্রধান রূপকার কাকে বলা হয়?',
      questionBengaliText: 'ভারতের সংবিধানের জনক ও প্রধান রূপকার কাকে বলা হয়?',
      optionA: 'ড. বি. আর. আম্বেদকর',
      optionB: 'মহাত্মা গান্ধী',
      optionC: 'জওহরলাল নেহরু',
      optionD: 'ড. রাজেন্দ্র প্রসাদ',
      correctOption: 'A',
      explanation:
        'ড. ভীমরাও রামজি আম্বেদকর সংবিধানের খসড়া কমিটির সভাপতি ছিলেন এবং তাঁকেই ভারতীয় সংবিধানের জনক বলা হয়।',
      explanationBengali:
        'ড. ভীমরাও রামজি আম্বেদকর সংবিধানের খসড়া কমিটির সভাপতি ছিলেন এবং তাঁকেই ভারতীয় সংবিধানের জনক বলা হয়।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'other',
      sourceExam: 'wbp-constable',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-mock-03',
      questionText: 'মানবদেহের স্বাভাবিক রক্তচাপ (Blood Pressure) কত?',
      questionBengaliText: 'মানবদেহের স্বাভাবিক রক্তচাপ (Blood Pressure) কত?',
      optionA: '১২০/৮০ মিমি পারদ স্তম্ভ',
      optionB: '১৪০/৯০ মিমি পারদ স্তম্ভ',
      optionC: '১০০/৬০ মিমি পারদ স্তম্ভ',
      optionD: '৮০/১২০ মিমি পারদ স্তম্ভ',
      correctOption: 'A',
      explanation:
        'সুস্থ প্রাপ্তবয়স্ক মানুষের স্বাভাবিক রক্তচাপ হলো ১২০/৮০ mmHg (সিস্টোলিক ১২০ ও ডায়াস্টোলিক ৮০ মিমি পারদ স্তম্ভ)।',
      explanationBengali:
        'সুস্থ প্রাপ্তবয়স্ক মানুষের স্বাভাবিক রক্তচাপ হলো ১২০/৮০ mmHg (সিস্টোলিক ১২০ ও ডায়াস্টোলিক ৮০ মিমি পারদ স্তম্ভ)।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'other',
      sourceExam: 'wbp-constable',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-mock-04',
      questionText: "কোষের 'শক্তিঘর' (Powerhouse of the Cell) কাকে বলা হয়?",
      questionBengaliText: "কোষের 'শক্তিঘর' (Powerhouse of the Cell) কাকে বলা হয়?",
      optionA: 'রাইবোজোম',
      optionB: 'লাইসোজোম',
      optionC: 'মাইটোকনড্রিয়া',
      optionD: 'গলগি বডি',
      correctOption: 'C',
      explanation:
        'মাইটোকনড্রিয়ায় শ্বসনের মাধ্যমে কোষীয় শক্তি ATP উৎপন্ন ও সঞ্চিত থাকে বলে একে কোষের শক্তিঘর বলা হয়।',
      explanationBengali:
        'মাইটোকনড্রিয়ায় শ্বসনের মাধ্যমে কোষীয় শক্তি ATP উৎপন্ন ও সঞ্চিত থাকে বলে একে কোষের শক্তিঘর বলা হয়।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'other',
      sourceExam: 'wbp-constable',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-mock-05',
      questionText: 'পশ্চিমবঙ্গের সরকারি রাজ্য পশু (State Animal) কোনটি?',
      questionBengaliText: 'পশ্চিমবঙ্গের সরকারি রাজ্য পশু (State Animal) কোনটি?',
      optionA: 'রয়্যাল বেঙ্গল টাইগার',
      optionB: 'মেছো বিড়াল (Fishing Cat)',
      optionC: 'একশৃঙ্গ গণ্ডার',
      optionD: 'চিতাবাঘ',
      correctOption: 'B',
      explanation: 'পশ্চিমবঙ্গের সরকারি রাজ্য পশু হলো মেছো বিড়াল বা বাঘরোল (Fishing Cat)।',
      explanationBengali: 'পশ্চিমবঙ্গের সরকারি রাজ্য পশু হলো মেছো বিড়াল বা বাঘরোল (Fishing Cat)।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'other',
      sourceExam: 'wbp-constable',
      isActive: true,
      status: 'active',
    },
  ],
  'test-wbp-pyq-2024': [
    {
      id: 'q-wbp-pyq-01',
      questionText: "কোন নদীকে ঐতিহাসিকভাবে 'বাংলার দুঃখ' বলা হতো?",
      questionBengaliText: "কোন নদীকে ঐতিহাসিকভাবে 'বাংলার দুঃখ' বলা হতো?",
      optionA: 'গঙ্গা নদী',
      optionB: 'দামোদর নদ',
      optionC: 'তিস্তা নদী',
      optionD: 'রূপনারায়ণ নদী',
      correctOption: 'B',
      explanation: 'বিধ্বংসী বন্যার কারণে অতীতে দামোদর নদকে বাংলার দুঃখ বলা হতো।',
      explanationBengali: 'বিধ্বংসী বন্যার কারণে অতীতে দামোদর নদকে বাংলার দুঃখ বলা হতো।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'pyq',
      sourceExam: 'wbp-constable',
      sourceYear: 2024,
      sourcePaper: 'WBP Preliminary Question Paper 2024',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-pyq-02',
      questionText: 'পশ্চিমবঙ্গের বর্তমান সর্বোচ্চ পর্বতশৃঙ্গ কোনটি?',
      questionBengaliText: 'পশ্চিমবঙ্গের বর্তমান সর্বোচ্চ পর্বতশৃঙ্গ কোনটি?',
      optionA: 'সান্দাকফু',
      optionB: 'ফালুট',
      optionC: 'সবরগ্রাম',
      optionD: 'টাইগার হিল',
      correctOption: 'A',
      explanation:
        'সান্দাকফু (উচ্চতা ৩,৬৩৬ মিটার) হলো পশ্চিমবঙ্গ তথা সিঙ্গালীলা পর্বতমালার সর্বোচ্চ শৃঙ্গ।',
      explanationBengali:
        'সান্দাকফু (উচ্চতা ৩,৬৩৬ মিটার) হলো পশ্চিমবঙ্গ তথা সিঙ্গালীলা পর্বতমালার সর্বোচ্চ শৃঙ্গ।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'pyq',
      sourceExam: 'wbp-constable',
      sourceYear: 2024,
      sourcePaper: 'WBP Preliminary Question Paper 2024',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-pyq-03',
      questionText: 'স্বাধীন ভারতে প্রথম সাধারণ নির্বাচন কোন সালে অনুষ্ঠিত হয়েছিল?',
      questionBengaliText: 'স্বাধীন ভারতে প্রথম সাধারণ নির্বাচন কোন সালে অনুষ্ঠিত হয়েছিল?',
      optionA: '১৯৪৭-৪৮ সালে',
      optionB: '১৯৫০-৫১ সালে',
      optionC: '১৯৫১-৫২ সালে',
      optionD: '১৯৫৫-৫৬ সালে',
      correctOption: 'C',
      explanation: 'স্বাধীন ভারতে প্রথম সাধারণ নির্বাচন ১৯৫১-৫২ সালে অনুষ্ঠিত হয়।',
      explanationBengali: 'স্বাধীন ভারতে প্রথম সাধারণ নির্বাচন ১৯৫১-৫২ সালে অনুষ্ঠিত হয়।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'pyq',
      sourceExam: 'wbp-constable',
      sourceYear: 2024,
      sourcePaper: 'WBP Preliminary Question Paper 2024',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-pyq-04',
      questionText:
        'বায়ুমণ্ডলের কোন স্তরে মেঘ, বৃষ্টি, কুয়াশা ইত্যাদি যাবতীয় আবহাওয়ার ঘটনা ঘটে?',
      questionBengaliText:
        'বায়ুমণ্ডলের কোন স্তরে মেঘ, বৃষ্টি, কুয়াশা ইত্যাদি যাবতীয় আবহাওয়ার ঘটনা ঘটে?',
      optionA: 'ট্রপোস্ফিয়ার',
      optionB: 'স্ট্র্যাটোস্ফিয়ার',
      optionC: 'মেসোস্ফিয়ার',
      optionD: 'থার্মোস্ফিয়ার',
      correctOption: 'A',
      explanation:
        'বায়ুমণ্ডলের সর্বনিম্ন স্তর ট্রপোস্ফিয়ারে যাবতীয় প্রাকৃতিক ও আবহাওয়া সংক্রান্ত ক্রিয়া-প্রতিক্রিয়া ঘটে।',
      explanationBengali:
        'বায়ুমণ্ডলের সর্বনিম্ন স্তর ট্রপোস্ফিয়ারে যাবতীয় প্রাকৃতিক ও আবহাওয়া সংক্রান্ত ক্রিয়া-প্রতিক্রিয়া ঘটে।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'pyq',
      sourceExam: 'wbp-constable',
      sourceYear: 2024,
      sourcePaper: 'WBP Preliminary Question Paper 2024',
      isActive: true,
      status: 'active',
    },
  ],
  'topic-math-ratio': [
    {
      id: 'q-math-ratio-01',
      subjectId: 'wbp-math',
      chapterId: 'wbp-math-ratio',
      topicId: 'wbp-math-ratio',
      questionText: 'A এবং B এর বয়সের অনুপাত 4:5 এবং তাদের বয়সের সমষ্টি 36 বছর হলে B এর বয়স কত?',
      questionBengaliText:
        'A এবং B এর বয়সের অনুপাত 4:5 এবং তাদের বয়সের সমষ্টি 36 বছর হলে B এর বয়স কত?',
      optionA: '16 বছর',
      optionB: '20 বছর',
      optionC: '24 বছর',
      optionD: '18 বছর',
      correctOption: 'B',
      explanation:
        'মোট ভাগ = 4 + 5 = 9। 9 ভাগ = 36 বছর, সুতরাং 1 ভাগ = 4 বছর। B এর বয়স = 5 × 4 = 20 বছর।',
      explanationBengali:
        'মোট ভাগ = 4 + 5 = 9। 9 ভাগ = 36 বছর, সুতরাং 1 ভাগ = 4 বছর। B এর বয়স = 5 × 4 = 20 বছর।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-math-ratio-02',
      subjectId: 'wbp-math',
      chapterId: 'wbp-math-ratio',
      topicId: 'wbp-math-ratio',
      questionText: 'যদি A : B = 2 : 3 এবং B : C = 4 : 5 হয়, তবে A : C এর মান কত?',
      questionBengaliText: 'যদি A : B = 2 : 3 এবং B : C = 4 : 5 হয়, তবে A : C এর মান কত?',
      optionA: '8 : 15',
      optionB: '6 : 15',
      optionC: '2 : 5',
      optionD: '15 : 8',
      correctOption: 'A',
      explanation: 'A/C = (A/B) × (B/C) = (2/3) × (4/5) = 8/15। অতএব A:C = 8:15।',
      explanationBengali: 'A/C = (A/B) × (B/C) = (2/3) × (4/5) = 8/15। অতএব A:C = 8:15।',
      difficulty: 'medium',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
  'topic-math-percentage': [
    {
      id: 'q-math-perc-01',
      subjectId: 'wbp-math',
      chapterId: 'wbp-math-percentage',
      topicId: 'wbp-math-percentage',
      questionText:
        'একটি বইয়ের ধার্যমূল্য 120 টাকা। বইটি 10% ছাড়ে বিক্রি করা হলে বিক্রয়মূল্য কত?',
      questionBengaliText:
        'একটি বইয়ের ধার্যমূল্য 120 টাকা। বইটি 10% ছাড়ে বিক্রি করা হলে বিক্রয়মূল্য কত?',
      optionA: '100 টাকা',
      optionB: '108 টাকা',
      optionC: '110 টাকা',
      optionD: '112 টাকা',
      correctOption: 'B',
      explanation: 'ছাড় = 120 × (10/100) = 12 টাকা। বিক্রয়মূল্য = 120 - 12 = 108 টাকা।',
      explanationBengali: 'ছাড় = 120 × (10/100) = 12 টাকা। বিক্রয়মূল্য = 120 - 12 = 108 টাকা।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
  'topic-sci-physics': [
    {
      id: 'q-sci-phys-01',
      subjectId: 'wbp-science',
      chapterId: 'wbp-sci-physics',
      topicId: 'wbp-sci-physics',
      questionText: 'SI পদ্ধতিতে বলের (Force) একক কী?',
      questionBengaliText: 'SI পদ্ধতিতে বলের (Force) একক কী?',
      optionA: 'ডাইন',
      optionB: 'নিউটন',
      optionC: 'জুল',
      optionD: 'ওয়াট',
      correctOption: 'B',
      explanation: 'SI পদ্ধতিতে বলের পরম একক হলো নিউটন (Newton), এবং CGS পদ্ধতিতে ডাইন।',
      explanationBengali: 'SI পদ্ধতিতে বলের পরম একক হলো নিউটন (Newton), এবং CGS পদ্ধতিতে ডাইন।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
  'topic-pol-rights': [
    {
      id: 'q-pol-rights-01',
      subjectId: 'wbp-polity',
      chapterId: 'wbp-pol-rights',
      topicId: 'wbp-pol-rights',
      questionText: 'ভারতীয় সংবিধানের কত নম্বর ধারায় অস্পৃশ্যতা দূরীকরণের কথা বলা হয়েছে?',
      questionBengaliText: 'ভারতীয় সংবিধানের কত নম্বর ধারায় অস্পৃশ্যতা দূরীকরণের কথা বলা হয়েছে?',
      optionA: 'ধারা 14',
      optionB: 'ধারা 17',
      optionC: 'ধারা 19',
      optionD: 'ধারা 21',
      correctOption: 'B',
      explanation:
        'সংবিধানের 17 নম্বর অনুচ্ছেদে অস্পৃশ্যতা বিলোপ (Abolition of Untouchability) এবং যে কোনো রূপে এর আচরণ নিষিদ্ধ করা হয়েছে।',
      explanationBengali:
        'সংবিধানের 17 নম্বর অনুচ্ছেদে অস্পৃশ্যতা বিলোপ (Abolition of Untouchability) এবং যে কোনো রূপে এর আচরণ নিষিদ্ধ করা হয়েছে।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0.25,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
};

export const MOCK_ATTEMPTS: TestAttempt[] = [
  {
    id: 'att-001',
    userId: 'usr-student-001',
    testId: 'test-indus-01',
    testTitle: 'Mock Test Part 01: Indus Valley (Free)',
    status: 'completed',
    startTime: '2025-02-10T14:00:00Z',
    endTime: '2025-02-10T14:11:30Z',
    timeSpentSeconds: 690,
    score: 4.75,
    totalMarks: 5.0,
    correctCount: 4,
    wrongCount: 1,
    skippedCount: 0,
    accuracy: 80.0,
    rank: 14,
    percentile: 94.5,
    createdAt: '2025-02-10T14:12:00Z',
  },
];

export const MOCK_MISTAKES: MistakeItem[] = [
  {
    id: 'mst-001',
    userId: 'usr-student-001',
    questionId: 'q-indus-05',
    question: MOCK_QUESTIONS['test-indus-01'][4],
    wrongCount: 2,
    isResolved: false,
    lastReviewedAt: '2025-02-10T14:15:00Z',
    createdAt: '2025-02-10T14:12:00Z',
  },
];

export const MOCK_BOOKMARKS: BookmarkItem[] = [
  {
    id: 'bm-001',
    userId: 'usr-student-001',
    questionId: 'q-indus-03',
    question: MOCK_QUESTIONS['test-indus-01'][2],
    note: 'সিন্ধু সভ্যতার প্রাচীন কৃত্রিম পোতাশ্রয় বা ডকইয়ার্ড সংক্রান্ত গুরুত্বপূর্ণ প্রশ্ন।',
    createdAt: '2025-02-10T14:13:00Z',
  },
];

export const MOCK_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'pro_1_year',
    title: '1-Year All-Access Pass',
    description:
      'Unlimited access to ALL Premium Mock Tests across all West Bengal exams for 365 days.',
    durationDays: 365,
    price: 299,
    originalPrice: 999,
    currency: 'INR',
    features: [
      'Unlock ALL Premium Mock Tests across all exams',
      'WBP Constable, KP SI, WBCS & WBPSC Clerkship',
      'Automatic Mistakes Notebook & Smart Revision',
      'Detailed Step-by-Step Explanations (Bengali & English)',
      'State-Level Rank & Percentile Analytics',
      'Validity: Full 365 Days',
    ],
    isActive: true,
    orderIndex: 1,
  },
  {
    id: 'pro_6_month',
    title: '6-Month Exam Pass',
    description: 'Complete access to all premium tests for 180 days.',
    durationDays: 180,
    price: 199,
    originalPrice: 599,
    currency: 'INR',
    features: [
      'Unlock ALL Premium Mock Tests',
      'Detailed Explanations & Solutions',
      'Mistakes Notebook & Bookmarks',
      'Validity: 180 Days',
    ],
    isActive: true,
    orderIndex: 2,
  },
];
