import {
  Exam,
  Subject,
  Chapter,
  MockTest,
  Question,
  TestAttempt,
  SubscriptionPlan,
  UserProfile,
  MistakeItem,
  BookmarkItem,
} from '@/types';

export const MOCK_STUDENT_USER: UserProfile = {
  id: 'usr-student-001',
  fullName: 'Subhamoy Banerjee',
  email: 'student@practicekoro.com',
  phone: '+91 98765 43210',
  avatarUrl:
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  targetExamId: 'wbp-constable',
  role: 'student',
  createdAt: '2025-01-10T10:00:00Z',
};

export const MOCK_ADMIN_USER: UserProfile = {
  id: 'usr-admin-001',
  fullName: 'Admin PracticeKoro',
  email: 'admin@practicekoro.online',
  phone: '+91 98300 12345',
  avatarUrl:
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  role: 'admin',
  createdAt: '2024-12-01T10:00:00Z',
};

export const MOCK_EXAMS: Exam[] = [
  {
    id: 'wbssc-group-d',
    title: 'WBSSC Group D',
    slug: 'wbssc-group-d',
    description: 'West Bengal School Service Commission Group D mock tests and syllabus practice.',
    category: 'West Bengal',
    iconName: 'Award',
    orderIndex: 1,
    isActive: true,
    testsCount: 25,
  },
  {
    id: 'wbp-constable',
    title: 'WBP Constable',
    slug: 'wbp-constable',
    description: 'West Bengal Police Constable Prelims & Mains Exam Mock Tests & Practice.',
    category: 'West Bengal',
    iconName: 'Shield',
    orderIndex: 2,
    isActive: true,
    testsCount: 15,
  },
  {
    id: 'wbpsc-clerkship',
    title: 'WBPSC Clerkship',
    slug: 'wbpsc-clerkship',
    description: 'WBPSC Lower Division Clerk Part-I Comprehensive Mock Tests.',
    category: 'West Bengal',
    iconName: 'GraduationCap',
    orderIndex: 3,
    isActive: true,
    testsCount: 20,
  },
  {
    id: 'primary-tet',
    title: 'Primary TET',
    slug: 'primary-tet',
    description: 'West Bengal Primary Teacher Eligibility Test comprehensive mock series.',
    category: 'Teaching',
    iconName: 'BookOpen',
    orderIndex: 4,
    isActive: true,
    testsCount: 12,
  },
  {
    id: 'wbssc-slst',
    title: 'WBSSC SLST',
    slug: 'wbssc-slst',
    description: 'State Level Selection Test for Assistant Teachers in West Bengal schools.',
    category: 'Teaching',
    iconName: 'Award',
    orderIndex: 5,
    isActive: true,
    testsCount: 10,
  },
  {
    id: 'ssc-gd',
    title: 'SSC GD',
    slug: 'ssc-gd',
    description: 'Staff Selection Commission General Duty Constable mock series.',
    category: 'Central',
    iconName: 'Shield',
    orderIndex: 6,
    isActive: true,
    testsCount: 25,
  },
  {
    id: 'ssc-cgl',
    title: 'SSC CGL',
    slug: 'ssc-cgl',
    description: 'Staff Selection Commission Combined Graduate Level mock tests.',
    category: 'Central',
    iconName: 'Award',
    orderIndex: 7,
    isActive: true,
    testsCount: 20,
  },
  {
    id: 'ssc-mts',
    title: 'SSC MTS',
    slug: 'ssc-mts',
    description: 'Staff Selection Commission Multi-Tasking Staff examination mocks.',
    category: 'Central',
    iconName: 'Layers',
    orderIndex: 8,
    isActive: true,
    testsCount: 15,
  },
  {
    id: 'railway-ntpc',
    title: 'Railway (NTPC)',
    slug: 'railway-ntpc',
    description: 'RRB Non-Technical Popular Categories CBT-1 & CBT-2 full mock tests.',
    category: 'Railway',
    iconName: 'Compass',
    orderIndex: 9,
    isActive: true,
    testsCount: 18,
  },
  {
    id: 'upper-primary-tet',
    title: 'Upper Primary TET',
    slug: 'upper-primary-tet',
    description: 'West Bengal Upper Primary TET preparation mocks and topic tests.',
    category: 'Teaching',
    iconName: 'BookOpen',
    orderIndex: 10,
    isActive: true,
    testsCount: 8,
  },
  {
    id: 'ctet',
    title: 'CTET',
    slug: 'ctet',
    description: 'Central Teacher Eligibility Test Paper 1 & Paper 2 mocks.',
    category: 'Teaching',
    iconName: 'GraduationCap',
    orderIndex: 11,
    isActive: true,
    testsCount: 15,
  },
  {
    id: 'wbcs-prelims',
    title: 'WBCS Executive Prelims',
    slug: 'wbcs-prelims',
    description: 'West Bengal Civil Service (Executive) Preliminary 200 Marks Mock Series.',
    category: 'Other',
    iconName: 'FileCheck',
    orderIndex: 12,
    isActive: true,
    testsCount: 30,
  },
  {
    id: 'kp-police-si',
    title: 'Kolkata Police SI',
    slug: 'kolkata-police-si',
    description: 'Kolkata Police Sub-Inspector & Sergeant Recruitment Examination.',
    category: 'Other',
    iconName: 'Award',
    orderIndex: 13,
    isActive: true,
    testsCount: 16,
  },
  {
    id: 'rrb-group-d',
    title: 'RRB Group D',
    slug: 'rrb-group-d',
    description: 'Railway Recruitment Cell Group D CBT examination mock test series.',
    category: 'Railway',
    iconName: 'Compass',
    orderIndex: 14,
    isActive: true,
    testsCount: 22,
  },
];

export const MOCK_SUBJECTS: Record<string, Subject[]> = {
  universal: [
    {
      id: 'wbp-history',
      name: 'Indian History',
      slug: 'indian-history',
      description: 'Ancient, Medieval, and Modern Indian history with Bengal Renaissance.',
      iconName: 'BookOpen',
      orderIndex: 1,
      isActive: true,
      chaptersCount: 12,
    },
    {
      id: 'wbp-math',
      name: 'Elementary Mathematics',
      slug: 'mathematics',
      description: 'Arithmetic, percentages, profit & loss, ratio & proportion, time & work.',
      iconName: 'Calculator',
      orderIndex: 2,
      isActive: true,
      chaptersCount: 15,
    },
    {
      id: 'wbp-science',
      name: 'General Science',
      slug: 'general-science',
      description: 'Physics, Chemistry, and Life Sciences as per secondary level syllabus.',
      iconName: 'FlaskConical',
      orderIndex: 3,
      isActive: true,
      chaptersCount: 10,
    },
    {
      id: 'wbp-polity',
      name: 'Indian Constitution & Geography',
      slug: 'indian-constitution',
      description: 'Preamble, Fundamental Rights, Parliament, and Geography of India & Bengal.',
      iconName: 'Scale',
      orderIndex: 4,
      isActive: true,
      chaptersCount: 8,
    },
    {
      id: 'wbp-bengali',
      name: 'Bengali Literature & Language',
      slug: 'bengali-literature',
      description: 'Classical Bengali literature, renowned authors, works, and grammar.',
      iconName: 'BookOpen',
      orderIndex: 5,
      isActive: true,
      chaptersCount: 6,
    },
  ],
};

export const MOCK_CHAPTERS: Record<string, Chapter[]> = {
  'wbp-bengali': [
    {
      id: 'wbp-bengali-lit',
      subjectId: 'wbp-bengali',
      name: 'Bengali Literature',
      slug: 'bengali-literature-classics',
      description: 'Poetry collections, novels, dramas, and literary biographies.',
      orderIndex: 1,
      isActive: true,
    },
  ],
  'wbp-history': [
    {
      id: 'wbp-hist-indus',
      subjectId: 'wbp-history',
      name: 'Indus Valley Civilization',
      slug: 'indus-valley-civilization',
      description: 'Harappa, Mohenjodaro, urban planning, seals, trade, and culture.',
      orderIndex: 1,
      isActive: true,
    },
    {
      id: 'wbp-hist-vedic',
      subjectId: 'wbp-history',
      name: 'Vedic Period & Buddhism',
      slug: 'vedic-period-buddhism',
      description: 'Early and Later Vedic society, literature, Jainism, Buddhism councils.',
      orderIndex: 2,
      isActive: true,
    },
    {
      id: 'wbp-hist-maurya',
      subjectId: 'wbp-history',
      name: 'Mauryan & Gupta Empire',
      slug: 'maurya-gupta-empire',
      description: 'Chandragupta Maurya, Ashoka inscriptions, Samudragupta, golden age.',
      orderIndex: 3,
      isActive: true,
    },
    {
      id: 'wbp-hist-freedom',
      subjectId: 'wbp-history',
      name: 'Indian Freedom Movement',
      slug: 'freedom-movement',
      description: 'Revolt of 1857, INA, Swadeshi movement, Gandhi era, partition.',
      orderIndex: 4,
      isActive: true,
    },
  ],
  'wbp-math': [
    {
      id: 'wbp-math-ratio',
      subjectId: 'wbp-math',
      name: 'Ratio & Proportion',
      slug: 'ratio-and-proportion',
      description: 'Ratio, proportion, and partnership business math shortcuts.',
      orderIndex: 1,
      isActive: true,
    },
    {
      id: 'wbp-math-percentage',
      subjectId: 'wbp-math',
      name: 'Percentage, Profit & Loss',
      slug: 'percentage-profit-loss',
      description: 'Percentage calculation, cost price, selling price, and discounts.',
      orderIndex: 2,
      isActive: true,
    },
    {
      id: 'wbp-math-time',
      subjectId: 'wbp-math',
      name: 'Time & Work',
      slug: 'time-and-work',
      description: 'Time and work, pipes and cisterns problem solving techniques.',
      orderIndex: 3,
      isActive: true,
    },
  ],
  'wbp-science': [
    {
      id: 'wbp-sci-physics',
      subjectId: 'wbp-science',
      name: 'General Physics',
      slug: 'general-physics',
      description: 'Motion, force, work, energy, and power core principles and applications.',
      orderIndex: 1,
      isActive: true,
    },
    {
      id: 'wbp-sci-life',
      subjectId: 'wbp-science',
      name: 'Life Science & Physiology',
      slug: 'life-science-human-body',
      description: 'Cell biology, tissues, digestive system, circulation, and vitamins.',
      orderIndex: 2,
      isActive: true,
    },
  ],
  'wbp-polity': [
    {
      id: 'wbp-pol-rights',
      subjectId: 'wbp-polity',
      name: 'Fundamental Rights & DPSP',
      slug: 'fundamental-rights-dpsp',
      description: 'Part III & IV of the Indian Constitution: Articles, Rights, and Duties.',
      orderIndex: 1,
      isActive: true,
    },
    {
      id: 'wbp-pol-preamble',
      subjectId: 'wbp-polity',
      name: 'Preamble & Parliament',
      slug: 'preamble-and-parliament',
      description: 'Constitutional preamble, President, Lok Sabha, and Rajya Sabha functions.',
      orderIndex: 2,
      isActive: true,
    },
  ],
};

export const MOCK_TEST_SERIES: Record<string, import('@/types').TestSeries[]> = {
  'wbp-constable': [
    {
      id: 'wbp-prelims-2025',
      examId: 'wbp-constable',
      title: 'WBP Constable 2025 Prelims Test Series',
      slug: 'wbp-prelims-2025',
      description: 'Official pattern 85-question full mocks and chapter drills.',
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      createdAt: '2026-01-01T00:00:00Z',
      examTitle: 'WBP Constable',
    },
    {
      id: 'wbp-mains-pro',
      examId: 'wbp-constable',
      title: 'WBP Constable Mains Pro Series',
      slug: 'wbp-mains-pro',
      description: 'Advanced mains test series with detailed step-by-step solutions.',
      isPremium: true,
      orderIndex: 2,
      isActive: true,
      createdAt: '2026-01-01T00:00:00Z',
      examTitle: 'WBP Constable',
    },
  ],
};

export const MOCK_TESTS: Record<string, MockTest[]> = {
  'wbp-hist-indus': [
    {
      id: 'test-indus-01',
      examId: 'wbp-constable',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      testSeriesId: 'wbp-prelims-2025',
      title: 'Mock Test Part 01: Indus Valley (Free)',
      slug: 'indus-valley-mock-01',
      description: 'Essential high-yield questions on Harappa & Mohenjodaro discoveries.',
      testType: 'chapter_mock',
      durationMinutes: 15,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0,
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'Indian History',
      chapterName: 'Indus Valley Civilization',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
    {
      id: 'test-indus-02',
      examId: 'wbp-constable',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      testSeriesId: 'wbp-prelims-2025',
      title: 'Mock Test Part 02: High-Yield Indus (Premium)',
      slug: 'indus-valley-mock-02',
      description: 'Advanced questions on archaeological sites, seals, religion and trade.',
      testType: 'chapter_mock',
      durationMinutes: 20,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0,
      isPremium: true,
      orderIndex: 2,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'Indian History',
      chapterName: 'Indus Valley Civilization',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
    {
      id: 'test-indus-03',
      examId: 'wbp-constable',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      testSeriesId: 'wbp-prelims-2025',
      title: 'Mock Test Part 03: PYQ Mastery (Premium)',
      slug: 'indus-valley-mock-03',
      description: 'Past 10 years WBPRB and WBPSC exam question compilation with explanations.',
      testType: 'chapter_mock',
      durationMinutes: 20,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0,
      isPremium: true,
      orderIndex: 3,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'Indian History',
      chapterName: 'Indus Valley Civilization',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
  ],
  'wbp-bengali': [
    {
      id: 'test-bengali-lit-01',
      examId: 'wbp-constable',
      subjectId: 'wbp-bengali',
      chapterId: 'wbp-bengali-lit',
      testSeriesId: 'wbp-prelims-2025',
      title: 'Bengali Literature Classics (Mock 01)',
      slug: 'bengali-literature-mock-01',
      description:
        'Essential practice questions on Rabindranath, Bankimchandra, and classical Bengali literature.',
      testType: 'chapter_mock',
      durationMinutes: 15,
      totalQuestions: 3,
      totalMarks: 3,
      passingMarks: 1,
      negativeMarking: 0,
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      subjectName: 'Bengali Literature & Language',
      chapterName: 'Bengali Literature',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
  ],
  'wbp-full-mocks': [
    {
      id: 'test-wbp-mock-01',
      examId: 'wbp-constable',
      testSeriesId: 'wbp-prelims-2025',
      title: 'WBP Preliminary Mock Test 01',
      slug: 'wbp-preliminary-mock-test-01',
      description: 'Comprehensive Full Mock Test based on latest WBPRB syllabus and marks pattern.',
      testType: 'full_mock',
      durationMinutes: 60,
      totalQuestions: 5,
      totalMarks: 5,
      passingMarks: 2,
      negativeMarking: 0.25,
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
    {
      id: 'test-wbp-mock-02',
      examId: 'wbp-constable',
      title: 'WBP Preliminary Mock Test 02',
      slug: 'wbp-preliminary-mock-test-02',
      description:
        'Full Length preliminary mock test with updated general awareness and reasoning.',
      testType: 'full_mock',
      durationMinutes: 60,
      totalQuestions: 0,
      totalMarks: 85,
      passingMarks: 40,
      negativeMarking: 0.25,
      isPremium: true,
      orderIndex: 2,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
    },
  ],
  'wbp-pyqs': [
    {
      id: 'test-wbp-pyq-2024',
      examId: 'wbp-constable',
      testSeriesId: 'wbp-prelims-2025',
      title: 'WBP Preliminary Question Paper 2024',
      paperName: 'WBP Preliminary Question Paper 2024',
      slug: 'wbp-preliminary-question-paper-2024',
      description: 'Official solved question paper of WBP Preliminary Exam 2024.',
      testType: 'pyq',
      year: 2024,
      durationMinutes: 60,
      totalQuestions: 4,
      totalMarks: 4,
      passingMarks: 2,
      negativeMarking: 0.25,
      isPremium: false,
      orderIndex: 1,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
      testSeriesTitle: 'WBP Constable 2025 Prelims Test Series',
    },
    {
      id: 'test-wbp-pyq-2023',
      examId: 'wbp-constable',
      title: 'WBP Preliminary Question Paper 2023',
      paperName: 'WBP Preliminary Question Paper 2023',
      slug: 'wbp-preliminary-question-paper-2023',
      description: 'Official solved question paper of WBP Preliminary Exam 2023.',
      testType: 'pyq',
      year: 2023,
      durationMinutes: 60,
      totalQuestions: 0,
      totalMarks: 85,
      passingMarks: 40,
      negativeMarking: 0.25,
      isPremium: false,
      orderIndex: 2,
      isActive: true,
      status: 'published',
      examTitle: 'WBP Constable',
    },
  ],
};

export const MOCK_QUESTIONS: Record<string, Question[]> = {
  'test-bengali-lit-01': [
    {
      id: 'q-lit-01',
      subjectId: 'wbp-bengali',
      chapterId: 'wbp-bengali-lit',
      topicId: 'wbp-bengali-lit',
      questionText: "In which year was Rabindranath Tagore's poetic work 'Gitanjali' published in Bengali?",
      questionBengaliText: "রবীন্দ্রনাথ ঠাকুরের 'গীতাঞ্জলি' কাব্যগ্রন্থটি কোন সালে প্রকাশিত হয়?",
      optionA: '1910',
      optionB: '1912',
      optionC: '1914',
      optionD: '1916',
      correctOption: 'A',
      explanation:
        "• Rabindranath Tagore's timeless poetry collection 'Gitanjali' was originally published in Bengali in 1910.\n• In 1912, its English translation 'Song Offerings' was published by the India Society of London.\n• In 1913, Tagore was awarded the Nobel Prize in Literature for Gitanjali, making him the first Asian Nobel laureate.\n• The introduction to the English Gitanjali was written by the renowned Irish poet W. B. Yeats.\n• The original Bengali collection contains 157 songs and poems.",
      explanationBengali:
        "• রবীন্দ্রনাথ ঠাকুরের কালজয়ী কাব্যগ্রন্থ 'গীতাঞ্জলি' মূল বাংলায় ১৯১০ সালে প্রকাশিত হয়।\n• ১৯১২ সালে লন্ডনের ইন্ডিয়া সোসাইটি থেকে এর ইংরেজি রূপান্তর 'Song Offerings' প্রকাশিত হয়েছিল।\n• ১৯১৩ সালে গীতাঞ্জলির জন্য রবীন্দ্রনাথ ঠাকুর প্রথম ভারতীয় ও এশীয় হিসেবে সাহিত্যে নোবেল পুরস্কার লাভ করেন।\n• ইংরেজি গীতাঞ্জলির ভূমিকা (Introduction) লিখেছিলেন বিখ্যাত আইরিশ কবি ডব্লিউ. বি. ইয়েটস (W. B. Yeats)।\n• মূল বাংলা গীতাঞ্জলি গ্রন্থে মোট ১৫৭টি গান ও কবিতা সংকলিত হয়েছে।",
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-lit-02',
      subjectId: 'wbp-bengali',
      chapterId: 'wbp-bengali-lit',
      topicId: 'wbp-bengali-lit',
      questionText: 'Which was the first successful full-length novel in Bengali literature?',
      questionBengaliText: 'বাংলা সাহিত্যের প্রথম সার্থক উপন্যাস কোনটি?',
      optionA: 'Alaler Gharer Dulal',
      optionB: 'Durgeshnandini',
      optionC: 'Kapalkundala',
      optionD: 'Chokher Bali',
      correctOption: 'B',
      explanation:
        "• Bankim Chandra Chattopadhyay's 'Durgeshnandini' (1865) is celebrated as the first successful modern novel in Bengali literature.\n• Set against the historical backdrop of Mughal-Pathan conflicts, it marks the dawn of modern prose fiction in Bengal.\n• Key characters include Jagat Singh, Tilottama, and Ayesha.\n• Bankim Chandra is widely regarded as the Father of the Bengali novel.\n• Other famous novels by Bankim include Kapalkundala (1866), Mrinalini (1869), and Bishabriksha (1873).",
      explanationBengali:
        "• সাহিত্যসম্রাট বঙ্কিমচন্দ্র চট্টোপাধ্যায়ের 'দুর্গেশনন্দিনী' (১৮৬৫) বাংলা সাহিত্যের প্রথম সার্থক উপন্যাস হিসেবে স্বীকৃত।\n• দুর্গেশনন্দিনী একটি ঐতিহাসিক রোমান্সধর্মী উপন্যাস যার পটভূমি ছিল মুঘল ও পাঠানদের মধ্যকার যুদ্ধ।\n• এই উপন্যাসের প্রধান চরিত্রগুলি হলো জগৎসিংহ, তিলোত্তমা ও আয়েষা।\n• এই উপন্যাস প্রকাশের পর বাংলা গদ্য সাহিত্য এক নতুন যুগে প্রবেশ করে এবং বঙ্কিমচন্দ্রকে বাংলা উপন্যাসের জনক বলা হয়।\n• বঙ্কিমচন্দ্রের অন্যান্য বিখ্যাত উপন্যাস হলো কপালকুণ্ডলা (১৮৬৬), মৃণালিনী (১৮৬৯) ও বিষবৃক্ষ (১৮৭৩)।",
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-lit-03',
      subjectId: 'wbp-bengali',
      chapterId: 'wbp-bengali-lit',
      topicId: 'wbp-bengali-lit',
      questionText:
        "From which famous novel of Bankim Chandra Chattopadhyay was the national song of India 'Vande Mataram' taken?",
      questionBengaliText:
        "ভারতের জাতীয় গান 'বন্দে মাতরম্' বঙ্কিমচন্দ্রের কোন উপন্যাস থেকে গৃহীত হয়েছে?",
      optionA: 'Anandamath',
      optionB: 'Devi Chaudhurani',
      optionC: 'Rajsimha',
      optionD: 'Sitaram',
      correctOption: 'A',
      explanation:
        "• India's national song 'Vande Mataram' was composed by Bankim Chandra Chattopadhyay and incorporated into his historic patriotic novel 'Anandamath' (1882).\n• The song was originally composed on 7th November 1875.\n• It was sung by Rabindranath Tagore in 1896 at the Calcutta session of the Indian National Congress.\n• On 24th January 1950, the Constituent Assembly of India officially adopted 'Vande Mataram' as the National Song.",
      explanationBengali:
        "• বঙ্কিমচন্দ্র চট্টোপাধ্যায়ের বিখ্যাত দেশাত্মবোধক উপন্যাস 'আনন্দমঠ' (১৮৮২) থেকে 'বন্দে মাতরম্' গানটি নেওয়া হয়েছে।\n• গানটি ১৮৭৫ সালের ৭ই নভেম্বর রচিত হয়েছিল এবং পরবর্তীতে আনন্দমঠ উপন্যাসে অন্তর্ভুক্ত করা হয়।\n• ১৭৭০ সালের ছিয়াত্তরের মন্বন্তর ও সন্ন্যাসী-ফকির বিদ্রোহের ঐতিহাসিক পটভূমিতে আনন্দমঠ উপন্যাসটি রচিত।\n• ১৮৯৬ সালে ভারতীয় জাতীয় কংগ্রেসের কলকাতা অধিবেশনে রবীন্দ্রনাথ ঠাকুর প্রথম এই গানটিতে সুরারোপ করে গান।\n• ১৯৫০ সালের ২৪শে জানুয়ারি ভারতের গণপরিষদ 'বন্দে মাতরম্'-কে ভারতের জাতীয় গান (National Song) হিসেবে স্বীকৃতি দেয়।",
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
  'test-indus-01': [
    {
      id: 'q-indus-01',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      topicId: 'wbp-hist-indus',
      questionText: '১৯২১ সালে হরপ্পা প্রত্নক্ষেত্রটি কে আবিষ্কার করেছিলেন?',
      questionBengaliText: '১৯২১ সালে হরপ্পা প্রত্নক্ষেত্রটি কে আবিষ্কার করেছিলেন?',
      optionA: 'রাখালদাস বন্দ্যোপাধ্যায়',
      optionB: 'দয়ারাম সাহনি',
      optionC: 'স্যার জন মার্শাল',
      optionD: 'আলেকজান্ডার কানিংহাম',
      correctOption: 'B',
      explanation:
        '• ১৯২১ সালে ভারতীয় প্রত্নতাত্ত্বিক রায়বাহাদুর দয়ারাম সাহনি ভারতীয় পুরাতত্ত্ব সর্বেক্ষণের অধীনে হরপ্পা আবিষ্কার করেন।\n• সেই সময় আর্কিওলজিক্যাল সার্ভে অব ইন্ডিয়ার (ASI) ডিরেক্টর জেনারেল ছিলেন স্যার জন মার্শাল।\n• হরপ্পা প্রত্নক্ষেত্রটি বর্তমান পাকিস্তানের পাঞ্জাব প্রদেশের শাহিওয়াল জেলায় ইরাবতী বা রাভি নদীর তীরে অবস্থিত।\n• হরপ্পা ছিল সিন্ধু সভ্যতার আবিষ্কৃত প্রথম শহর, তাই সমগ্র সভ্যতাকে হরপ্পা সভ্যতা বলা হয়।\n• হরপ্পা খননকার্য থেকে বিশাল শস্যভাণ্ডার (Great Granary), কফিনে সমাহিতকরণ ও মাতৃদেবীর মাটির মূর্তি পাওয়া গেছে।',
      explanationBengali:
        '• ১৯২১ সালে ভারতীয় প্রত্নতাত্ত্বিক রায়বাহাদুর দয়ারাম সাহনি ভারতীয় পুরাতত্ত্ব সর্বেক্ষণের অধীনে হরপ্পা আবিষ্কার করেন।\n• সেই সময় আর্কিওলজিক্যাল সার্ভে অব ইন্ডিয়ার (ASI) ডিরেক্টর জেনারেল ছিলেন স্যার জন মার্শাল।\n• হরপ্পা প্রত্নক্ষেত্রটি বর্তমান পাকিস্তানের পাঞ্জাব প্রদেশের শাহিওয়াল জেলায় ইরাবতী বা রাভি নদীর তীরে অবস্থিত।\n• হরপ্পা ছিল সিন্ধু সভ্যতার আবিষ্কৃত প্রথম শহর, তাই সমগ্র সভ্যতাকে হরপ্পা সভ্যতা বলা হয়।\n• হরপ্পা খননকার্য থেকে বিশাল শস্যভাণ্ডার (Great Granary), কফিনে সমাহিতকরণ ও মাতৃদেবীর মাটির মূর্তি পাওয়া গেছে।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-indus-02',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      topicId: 'wbp-hist-indus',
      questionText: 'সিন্ধু সভ্যতার বিখ্যাত বৃহৎ স্নানাগারটি (Great Bath) কোথায় পাওয়া গেছে?',
      questionBengaliText:
        'সিন্ধু সভ্যতার বিখ্যাত বৃহৎ স্নানাগারটি (Great Bath) কোথায় পাওয়া গেছে?',
      optionA: 'হরপ্পা',
      optionB: 'লোথাল',
      optionC: 'মহেঞ্জোদারো',
      optionD: 'কালিবঙ্গান',
      correctOption: 'C',
      explanation:
        '• সিন্ধু সভ্যতার সর্বাপেক্ষা চমকপ্রদ স্থাপত্য বৃহৎ স্নানাগারটি (Great Bath) মহেঞ্জোদারোতে অবস্থিত।\n• ১৯২২ সালে প্রখ্যাত বাঙালি প্রত্নতাত্ত্বিক রাখালদাস বন্দ্যোপাধ্যায় সিন্ধু প্রদেশের লারকানা জেলায় মহেঞ্জোদারো আবিষ্কার করেন।\n• স্নানাগারটির পরিমাপ প্রায় ৩৯ ফুট দীর্ঘ, ২৩ ফুট চওড়া এবং ৮ ফুট গভীর।\n• স্নানাগারের মেঝেকে জলনিরোধক করতে পোড়ামাটির ইট এবং প্রাকৃতিক বিটুমিনের প্রলেপ ব্যবহার করা হয়েছিল।\n• গবেষকদের মতে এটি সাধারণ ব্যবহারের জন্য নয় বরং ধর্মীয় বা আনুষ্ঠানিক শুদ্ধিকরণ অনুষ্ঠানে ব্যবহৃত হতো।',
      explanationBengali:
        '• সিন্ধু সভ্যতার সর্বাপেক্ষা চমকপ্রদ স্থাপত্য বৃহৎ স্নানাগারটি (Great Bath) মহেঞ্জোদারোতে অবস্থিত।\n• ১৯২২ সালে প্রখ্যাত বাঙালি প্রত্নতাত্ত্বিক রাখালদাস বন্দ্যোপাধ্যায় সিন্ধু প্রদেশের লারকানা জেলায় মহেঞ্জোদারো আবিষ্কার করেন।\n• স্নানাগারটির পরিমাপ প্রায় ৩৯ ফুট দীর্ঘ, ২৩ ফুট চওড়া এবং ৮ ফুট গভীর।\n• স্নানাগারের মেঝেকে জলনিরোধক করতে পোড়ামাটির ইট এবং প্রাকৃতিক বিটুমিনের প্রলেপ ব্যবহার করা হয়েছিল।\n• গবেষকদের মতে এটি সাধারণ ব্যবহারের জন্য নয় বরং ধর্মীয় বা আনুষ্ঠানিক শুদ্ধিকরণ অনুষ্ঠানে ব্যবহৃত হতো।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-indus-03',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      topicId: 'wbp-hist-indus',
      questionText: 'সিন্ধু সভ্যতার কোন শহরটিতে প্রাচীন কৃত্রিম পোতাশ্রয় বা ডকইয়ার্ড ছিল?',
      questionBengaliText: 'সিন্ধু সভ্যতার কোন শহরটিতে প্রাচীন কৃত্রিম পোতাশ্রয় বা ডকইয়ার্ড ছিল?',
      optionA: 'লোথাল',
      optionB: 'সুরকোটাদা',
      optionC: 'বনওয়ালি',
      optionD: 'রাখিগড়ী',
      correctOption: 'A',
      explanation:
        '• গুজরাটের আহমেদাবাদ জেলায় ভোগাবর নদীর তীরে অবস্থিত লোথাল ছিল সিন্ধু সভ্যতার একমাত্র প্রধান সামুদ্রিক বন্দর নগরী।\n• ১৯৫৪-১৯৫৮ সালে ভারতীয় পুরাতাত্ত্বিক এস. আর. রাও লোথাল প্রত্নক্ষেত্রটি আবিষ্কার ও খনন করেন।\n• লোথালে প্রাপ্ত পোতাশ্রয়টি (Tidal Dockyard) হলো বিশ্বের প্রাচীনতম জ্ঞাত কৃত্রিম ডকইয়ার্ড।\n• মেসোপটেমিয়ার সিলমোহর এবং ধানের তুষের প্রাচীনতম নিদর্শনও লোথাল থেকে আবিষ্কৃত হয়েছে।\n• লোথালকে হরপ্পা সভ্যতার আন্তর্জাতিক বাণিজ্য ও সমুদ্রপথের প্রবেশদ্বার হিসেবে বিবেচনা করা হতো।',
      explanationBengali:
        '• গুজরাটের আহমেদাবাদ জেলায় ভোগাবর নদীর তীরে অবস্থিত লোথাল ছিল সিন্ধু সভ্যতার একমাত্র প্রধান সামুদ্রিক বন্দর নগরী।\n• ১৯৫৪-১৯৫৮ সালে ভারতীয় পুরাতাত্ত্বিক এস. আর. রাও লোথাল প্রত্নক্ষেত্রটি আবিষ্কার ও খনন করেন।\n• লোথালে প্রাপ্ত পোতাশ্রয়টি (Tidal Dockyard) হলো বিশ্বের প্রাচীনতম জ্ঞাত কৃত্রিম ডকইয়ার্ড।\n• মেসোপটেমিয়ার সিলমোহর এবং ধানের তুষের প্রাচীনতম নিদর্শনও লোথাল থেকে আবিষ্কৃত হয়েছে।\n• লোথালকে হরপ্পা সভ্যতার আন্তর্জাতিক বাণিজ্য ও সমুদ্রপথের প্রবেশদ্বার হিসেবে বিবেচনা করা হতো।',
      difficulty: 'medium',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-indus-04',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      topicId: 'wbp-hist-indus',
      questionText: 'সিন্ধু সভ্যতা মূলত কোন ঐতিহাসিক যুগের অন্তর্গত ছিল?',
      questionBengaliText: 'সিন্ধু সভ্যতা মূলত কোন ঐতিহাসিক যুগের অন্তর্গত ছিল?',
      optionA: 'প্রাচীন প্রস্তর যুগ',
      optionB: 'মধ্য প্রস্তর যুগ',
      optionC: 'তাম্র-ব্রোঞ্জ যুগ',
      optionD: 'লৌহ যুগ',
      correctOption: 'C',
      explanation:
        '• সিন্ধু সভ্যতা বা হরপ্পা সভ্যতা প্রাগৈতিহাসিক তাম্র-ব্রোঞ্জ যুগের (Bronze Age) একটি সুপরিকল্পিত নগরকেন্দ্রিক সভ্যতা।\n• এই সভ্যতার আনুমানিক সময়সীমা ধরা হয় প্রায় খ্রিস্টপূর্ব ২৫০০ অব্দ থেকে ১৭৫০ অব্দ পর্যন্ত (রেডিওকার্বন C-14 পদ্ধতি অনুযায়ী)।\n• হরপ্পাবাসীরা তামা ও টিনের মিশ্রণে টেকসই ব্রোঞ্জ ধাতু তৈরিতে অত্যন্ত পারদর্শী ছিল।\n• হরপ্পা সভ্যতার মানুষের কাছে লোহার ব্যবহার সম্পূর্ণ অজানা ছিল; ভারতে লোহার ব্যবহার শুরু হয় বৈদিক যুগে।\n• উন্নত ভূগর্ভস্থ নিকাশী ব্যবস্থা ও গ্রিড পদ্ধতিতে গঠিত রাজপথ এই প্রাচীন সভ্যতার শ্রেষ্ঠ অবদান।',
      explanationBengali:
        '• সিন্ধু সভ্যতা বা হরপ্পা সভ্যতা প্রাগৈতিহাসিক তাম্র-ব্রোঞ্জ যুগের (Bronze Age) একটি সুপরিকল্পিত নগরকেন্দ্রিক সভ্যতা।\n• এই সভ্যতার আনুমানিক সময়সীমা ধরা হয় প্রায় খ্রিস্টপূর্ব ২৫০০ অব্দ থেকে ১৭৫০ অব্দ পর্যন্ত (রেডিওকার্বন C-14 পদ্ধতি অনুযায়ী)।\n• হরপ্পাবাসীরা তামা ও টিনের মিশ্রণে টেকসই ব্রোঞ্জ ধাতু তৈরিতে অত্যন্ত পারদর্শী ছিল।\n• হরপ্পা সভ্যতার মানুষের কাছে লোহার ব্যবহার সম্পূর্ণ অজানা ছিল; ভারতে লোহার ব্যবহার শুরু হয় বৈদিক যুগে।\n• উন্নত ভূগর্ভস্থ নিকাশী ব্যবস্থা ও গ্রিড পদ্ধতিতে গঠিত রাজপথ এই প্রাচীন সভ্যতার শ্রেষ্ঠ অবদান।',
      difficulty: 'medium',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-indus-05',
      subjectId: 'wbp-history',
      chapterId: 'wbp-hist-indus',
      topicId: 'wbp-hist-indus',
      questionText: 'সিন্ধু সভ্যতার কোন কেন্দ্রে লাঙল দেওয়া চাষের জমির প্রমাণ পাওয়া গেছে?',
      questionBengaliText: 'সিন্ধু সভ্যতার কোন কেন্দ্রে লাঙল দেওয়া চাষের জমির প্রমাণ পাওয়া গেছে?',
      optionA: 'চানহুদারো',
      optionB: 'কালিবঙ্গান',
      optionC: 'ধোলাভিরা',
      optionD: 'কোট দিজি',
      correctOption: 'B',
      explanation:
        '• রাজস্থানের হনুমানগড় জেলায় ঘর্ঘরা নদীর তীরে অবস্থিত কালিবঙ্গানে লাঙল দিয়ে চষা কৃষিজমির প্রাচীনতম প্রমাণ মিলেছে।\n• ১৯৫৩ সালে এ. ঘোষ (অমলানন্দ ঘোষ) কালিবঙ্গান প্রত্নক্ষেত্রটি প্রথম চিহ্নিত করেন এবং পরে বি. বি. লাল খনন পরিচালনা করেন।\n• কালিবঙ্গান শব্দের আক্ষরিক অর্থ হলো কালো চুড়ি (Black Bangles)।\n• এই প্রত্নক্ষেত্র থেকে যজ্ঞকুণ্ড বা অগ্নিকুণ্ডের (Fire Altars) অস্তিত্ব এবং উটের অস্থির সন্ধান পাওয়া গেছে।\n• সমকোণে তৈরি খাঁজ নির্দেশ করে যে একই জমিতে একসাথে দুটি শস্য (সরিষা ও ছোলা) চাষের উন্নত প্রযুক্তি তাদের জানা ছিল।',
      explanationBengali:
        '• রাজস্থানের হনুমানগড় জেলায় ঘর্ঘরা নদীর তীরে অবস্থিত কালিবঙ্গানে লাঙল দিয়ে চষা কৃষিজমির প্রাচীনতম প্রমাণ মিলেছে।\n• ১৯৫৩ সালে এ. ঘোষ (অমলানন্দ ঘোষ) কালিবঙ্গান প্রত্নক্ষেত্রটি প্রথম চিহ্নিত করেন এবং পরে বি. বি. লাল খনন পরিচালনা করেন।\n• কালিবঙ্গান শব্দের আক্ষরিক অর্থ হলো কালো চুড়ি (Black Bangles)।\n• এই প্রত্নক্ষেত্র থেকে যজ্ঞকুণ্ড বা অগ্নিকুণ্ডের (Fire Altars) অস্তিত্ব এবং উটের অস্থির সন্ধান পাওয়া গেছে।\n• সমকোণে তৈরি খাঁজ নির্দেশ করে যে একই জমিতে একসাথে দুটি শস্য (সরিষা ও ছোলা) চাষের উন্নত প্রযুক্তি তাদের জানা ছিল।',
      difficulty: 'hard',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
  'test-wbp-mock-01': [
    {
      id: 'q-wbp-mock-01',
      subjectId: 'wbp-science',
      subjectName: 'General Awareness',
      chapterName: 'Solar System & Astronomy',
      questionText: "আমাদের সৌরজগতের কোন গ্রহকে 'লাল গ্রহ' বলা হয়?",
      questionBengaliText: "আমাদের সৌরজগতের কোন গ্রহকে 'লাল গ্রহ' বলা হয়?",
      optionA: 'শুক্র',
      optionB: 'মঙ্গল',
      optionC: 'বৃহস্পতি',
      optionD: 'শনি',
      correctOption: 'B',
      explanation:
        '• মঙ্গল গ্রহের (Mars) পৃষ্ঠে প্রচুর পরিমাণে আয়রন অক্সাইড বা লোহার মরিচা থাকার কারণে এটি মহাকাশ থেকে লালচে দেখায়, তাই একে লাল গ্রহ বলে।\n• সৌরজগতের গ্রহগুলির মধ্যে সূর্যের দূরত্বের দিক থেকে এটি চতুর্থ এবং আকৃতির দিক থেকে দ্বিতীয় ক্ষুদ্রতম গ্রহ।\n• মঙ্গল গ্রহের দুটি ক্ষুদ্র প্রাকৃতিক উপগ্রহ রয়েছে— ফোবোস (Phobos) এবং ডিমোস (Deimos)।\n• সৌরজগতের সর্বোচ্চ আগ্নেয়গিরি ও পর্বত অলিম্পাস মনস (Olympus Mons) মঙ্গল গ্রহে অবস্থিত, যা এভারেস্টের চেয়ে প্রায় তিনগুণ উঁচু।\n• ভারত ২০১৪ সালে নিজস্ব প্রযুক্তিতে মঙ্গলায়ান (MOM) প্রথম প্রচেষ্টাতেই সফলভাবে মঙ্গলের কক্ষপথে স্থাপন করে।',
      explanationBengali:
        '• মঙ্গল গ্রহের (Mars) পৃষ্ঠে প্রচুর পরিমাণে আয়রন অক্সাইড বা লোহার মরিচা থাকার কারণে এটি মহাকাশ থেকে লালচে দেখায়, তাই একে লাল গ্রহ বলে।\n• সৌরজগতের গ্রহগুলির মধ্যে সূর্যের দূরত্বের দিক থেকে এটি চতুর্থ এবং আকৃতির দিক থেকে দ্বিতীয় ক্ষুদ্রতম গ্রহ।\n• মঙ্গল গ্রহের দুটি ক্ষুদ্র প্রাকৃতিক উপগ্রহ রয়েছে— ফোবোস (Phobos) এবং ডিমোস (Deimos)।\n• সৌরজগতের সর্বোচ্চ আগ্নেয়গিরি ও পর্বত অলিম্পাস মনস (Olympus Mons) মঙ্গল গ্রহে অবস্থিত, যা এভারেস্টের চেয়ে প্রায় তিনগুণ উঁচু।\n• ভারত ২০১৪ সালে নিজস্ব প্রযুক্তিতে মঙ্গলায়ান (MOM) প্রথম প্রচেষ্টাতেই সফলভাবে মঙ্গলের কক্ষপথে স্থাপন করে।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'other',
      sourceExam: 'wbp-constable',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-mock-02',
      subjectId: 'wbp-polity',
      subjectName: 'General Awareness',
      chapterName: 'Indian Constitution',
      questionText: 'ভারতের সংবিধানের জনক ও প্রধান রূপকার কাকে বলা হয়?',
      questionBengaliText: 'ভারতের সংবিধানের জনক ও প্রধান রূপকার কাকে বলা হয়?',
      optionA: 'ড. বি. আর. আম্বেদকর',
      optionB: 'মহাত্মা গান্ধী',
      optionC: 'জওহরলাল নেহরু',
      optionD: 'ড. রাজেন্দ্র প্রসাদ',
      correctOption: 'A',
      explanation:
        '• ড. ভীমরাও রামজি আম্বেদকর ছিলেন ভারতীয় সংবিধানের খসড়া কমিটির (Drafting Committee) সভাপতি।\n• ভারতের সংবিধান রচনার মূল কারিগর ও পথপ্রদর্শক হিসেবে তাঁকে ভারতীয় সংবিধানের জনক ও আধুনিক মনু বলা হয়।\n• ১৯৪৭ সালের ২৯শে আগস্ট গণপরিষদ ড. আম্বেদকরের নেতৃত্বে সাত সদস্যের খসড়া কমিটি গঠন করেছিল।\n• তিনি স্বাধীন ভারতের প্রথম আইন ও বিচারমন্ত্রী (Law and Justice Minister) হিসেবে দায়িত্ব পালন করেন।\n• ১৯৯০ সালে ড. বি. আর. আম্বেদকরকে মরণোত্তর ভারতের সর্বোচ্চ বেসামরিক সম্মান ভারতরত্ন প্রদান করা হয়।',
      explanationBengali:
        '• ড. ভীমরাও রামজি আম্বেদকর ছিলেন ভারতীয় সংবিধানের খসড়া কমিটির (Drafting Committee) সভাপতি।\n• ভারতের সংবিধান রচনার মূল কারিগর ও পথপ্রদর্শক হিসেবে তাঁকে ভারতীয় সংবিধানের জনক ও আধুনিক মনু বলা হয়।\n• ১৯৪৭ সালের ২৯শে আগস্ট গণপরিষদ ড. আম্বেদকরের নেতৃত্বে সাত সদস্যের খসড়া কমিটি গঠন করেছিল।\n• তিনি স্বাধীন ভারতের প্রথম আইন ও বিচারমন্ত্রী (Law and Justice Minister) হিসেবে দায়িত্ব পালন করেন।\n• ১৯৯০ সালে ড. বি. আর. আম্বেদকরকে মরণোত্তর ভারতের সর্বোচ্চ বেসামরিক সম্মান ভারতরত্ন প্রদান করা হয়।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'other',
      sourceExam: 'wbp-constable',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-mock-03',
      subjectId: 'wbp-science',
      subjectName: 'General Awareness',
      chapterName: 'Human Physiology',
      questionText: 'মানবদেহের স্বাভাবিক রক্তচাপ (Blood Pressure) কত?',
      questionBengaliText: 'মানবদেহের স্বাভাবিক রক্তচাপ (Blood Pressure) কত?',
      optionA: '১২০/৮০ মিমি পারদ স্তম্ভ',
      optionB: '১৪০/৯০ মিমি পারদ স্তম্ভ',
      optionC: '১০০/৬০ মিমি পারদ স্তম্ভ',
      optionD: '৮০/১২০ মিমি পারদ স্তম্ভ',
      correctOption: 'A',
      explanation:
        '• সুস্থ প্রাপ্তবয়স্ক মানুষের স্বাভাবিক রক্তচাপের আদর্শ মান হলো ১২০/৮০ মিমি পারদ স্তম্ভ (mmHg)।\n• ওপরের মান ১২০ mmHg হলো সিস্টোলিক চাপ (হৃৎপিণ্ডের সংকোচনের সময় রক্তের চাপ) এবং নিচের মান ৮০ mmHg হলো ডায়াস্টোলিক চাপ (হৃৎপিণ্ডের প্রসারণের সময় চাপ)।\n• রক্তচাপ পরিমাপ করার জন্য চিকিৎসাক্ষেত্রে স্ফিগমোম্যানোমিটার (Sphygmomanometer) যন্ত্র ব্যবহার করা হয়।\n• রক্তচাপ একটানা ১৪০/৯০ mmHg বা তার বেশি থাকলে তাকে উচ্চ রক্তচাপ বা হাইপারটেনশন বলে।\n• রক্তচাপ ৯০/৬০ mmHg-এর নিচে নেমে গেলে তাকে নিম্ন রক্তচাপ বা হাইপোটেনশন বলা হয়।',
      explanationBengali:
        '• সুস্থ প্রাপ্তবয়স্ক মানুষের স্বাভাবিক রক্তচাপের আদর্শ মান হলো ১২০/৮০ মিমি পারদ স্তম্ভ (mmHg)।\n• ওপরের মান ১২০ mmHg হলো সিস্টোলিক চাপ (হৃৎপিণ্ডের সংকোচনের সময় রক্তের চাপ) এবং নিচের মান ৮০ mmHg হলো ডায়াস্টোলিক চাপ (হৃৎপিণ্ডের প্রসারণের সময় চাপ)।\n• রক্তচাপ পরিমাপ করার জন্য চিকিৎসাক্ষেত্রে স্ফিগমোম্যানোমিটার (Sphygmomanometer) যন্ত্র ব্যবহার করা হয়।\n• রক্তচাপ একটানা ১৪০/৯০ mmHg বা তার বেশি থাকলে তাকে উচ্চ রক্তচাপ বা হাইপারটেনশন বলে।\n• রক্তচাপ ৯০/৬০ mmHg-এর নিচে নেমে গেলে তাকে নিম্ন রক্তচাপ বা হাইপোটেনশন বলা হয়।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'other',
      sourceExam: 'wbp-constable',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-mock-04',
      subjectId: 'wbp-science',
      subjectName: 'General Awareness',
      chapterName: 'Cell Biology',
      questionText: "কোষের 'শক্তিঘর' (Powerhouse of the Cell) কাকে বলা হয়?",
      questionBengaliText: "কোষের 'শক্তিঘর' (Powerhouse of the Cell) কাকে বলা হয়?",
      optionA: 'রাইবোজোম',
      optionB: 'লাইসোজোম',
      optionC: 'মাইটোকনড্রিয়া',
      optionD: 'গলগি বডি',
      correctOption: 'C',
      explanation:
        '• মাইটোকনড্রিয়ায় সবাত শ্বসনের ক্রেবস চক্র সম্পন্ন হয় এবং বিপুল পরিমাণ রাসায়নিক শক্তি ATP (এডিনোসিন ট্রাইফসফেট) তৈরি হয়।\n• কোষে প্রয়োজনীয় শক্তি এটিপি আকারে সঞ্চিত ও সরবরাহ করা হয় বলে মাইটোকনড্রিয়াকে কোষের শক্তিঘর বলা হয়।\n• ১৮৫৭ সালে আলবার্ট ভন কোলিকার পেশিকোষে প্রথম মাইটোকনড্রিয়া পর্যবেক্ষণ করেন এবং ১৮৯৮ সালে কার্ল বেন্দা এর নামকরণ করেন।\n• মাইটোকনড্রিয়া হলো একটি দ্বি-একক পর্দাবেষ্টিত অঙ্গাণু, যার নিজস্ব বৃত্তাকার ডিএনএ (mtDNA) ও রাইবোজোম রয়েছে।\n• কোষের আত্মঘাতী থলি বলা হয় লাইসোজোমকে এবং প্রোটিন তৈরির কারখানা বলা হয় রাইবোজোমকে।',
      explanationBengali:
        '• মাইটোকনড্রিয়ায় সবাত শ্বসনের ক্রেবস চক্র সম্পন্ন হয় এবং বিপুল পরিমাণ রাসায়নিক শক্তি ATP (এডিনোসিন ট্রাইফসফেট) তৈরি হয়।\n• কোষে প্রয়োজনীয় শক্তি এটিপি আকারে সঞ্চিত ও সরবরাহ করা হয় বলে মাইটোকনড্রিয়াকে কোষের শক্তিঘর বলা হয়।\n• ১৮৫৭ সালে আলবার্ট ভন কোলিকার পেশিকোষে প্রথম মাইটোকনড্রিয়া পর্যবেক্ষণ করেন এবং ১৮৯৮ সালে কার্ল বেন্দা এর নামকরণ করেন।\n• মাইটোকনড্রিয়া হলো একটি দ্বি-একক পর্দাবেষ্টিত অঙ্গাণু, যার নিজস্ব বৃত্তাকার ডিএনএ (mtDNA) ও রাইবোজোম রয়েছে।\n• কোষের আত্মঘাতী থলি বলা হয় লাইসোজোমকে এবং প্রোটিন তৈরির কারখানা বলা হয় রাইবোজোমকে।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'other',
      sourceExam: 'wbp-constable',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-mock-05',
      subjectId: 'wbp-polity',
      subjectName: 'General Awareness',
      chapterName: 'West Bengal GK',
      questionText: 'পশ্চিমবঙ্গের সরকারি রাজ্য পশু (State Animal) কোনটি?',
      questionBengaliText: 'পশ্চিমবঙ্গের সরকারি রাজ্য পশু (State Animal) কোনটি?',
      optionA: 'রয়্যাল বেঙ্গল টাইগার',
      optionB: 'মেছো বিড়াল (Fishing Cat)',
      optionC: 'একশৃঙ্গ গণ্ডার',
      optionD: 'চিতাবাঘ',
      correctOption: 'B',
      explanation:
        '• পশ্চিমবঙ্গের সরকারি রাজ্য পশু হলো মেছো বিড়াল বা বাঘরোল, যার বৈজ্ঞানিক নাম হলো Prionailurus viverrinus (Fishing Cat)।\n• এটি প্রধানত সুন্দরবনের ম্যানগ্রোভ অরণ্য এবং হাওড়া, হুগলি, পূর্ব মেদিনীপুরের জলাভূমি এলাকায় বাস করে।\n• পশ্চিমবঙ্গের অন্যান্য রাজ্য প্রতীক: রাজ্য পাখি হলো ধনেশ বা শ্বেতকণ্ঠ মাছরাঙা (White-throated Kingfisher)।\n• পশ্চিমবঙ্গের রাজ্য ফুল হলো শিউলি বা শেফালি (Night-flowering Jasmine) এবং রাজ্য বৃক্ষ হলো ছাতিম (Alstonia scholaris)।\n• মেছো বিড়াল সাঁতার কাটতে অত্যন্ত পারদর্শী এবং জল থেকে মাছ শিকার করে জীবনধারণ করে।',
      explanationBengali:
        '• পশ্চিমবঙ্গের সরকারি রাজ্য পশু হলো মেছো বিড়াল বা বাঘরোল, যার বৈজ্ঞানিক নাম হলো Prionailurus viverrinus (Fishing Cat)।\n• এটি প্রধানত সুন্দরবনের ম্যানগ্রোভ অরণ্য এবং হাওড়া, হুগলি, পূর্ব মেদিনীপুরের জলাভূমি এলাকায় বাস করে।\n• পশ্চিমবঙ্গের অন্যান্য রাজ্য প্রতীক: রাজ্য পাখি হলো ধনেশ বা শ্বেতকণ্ঠ মাছরাঙা (White-throated Kingfisher)।\n• পশ্চিমবঙ্গের রাজ্য ফুল হলো শিউলি বা শেফালি (Night-flowering Jasmine) এবং রাজ্য বৃক্ষ হলো ছাতিম (Alstonia scholaris)।\n• মেছো বিড়াল সাঁতার কাটতে অত্যন্ত পারদর্শী এবং জল থেকে মাছ শিকার করে জীবনধারণ করে।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'other',
      sourceExam: 'wbp-constable',
      isActive: true,
      status: 'active',
    },
  ],
  'test-wbp-pyq-2024': [
    {
      id: 'q-wbp-pyq-01',
      subjectId: 'wbp-polity',
      subjectName: 'General Awareness',
      chapterName: 'Geography of Bengal & India',
      questionText: "কোন নদীকে ঐতিহাসিকভাবে 'বাংলার দুঃখ' বলা হতো?",
      questionBengaliText: "কোন নদীকে ঐতিহাসিকভাবে 'বাংলার দুঃখ' বলা হতো?",
      optionA: 'গঙ্গা নদী',
      optionB: 'দামোদর নদ',
      optionC: 'তিস্তা নদী',
      optionD: 'রূপনারায়ণ নদী',
      correctOption: 'B',
      explanation:
        '• অতীতে বর্ষাকালে দামোদর নদের বিধ্বংসী বন্যায় বর্ধমান ও হুগলির বিস্তীর্ণ অঞ্চল প্লাবিত হতো বলে একে বাংলার দুঃখ (Sorrow of Bengal) বলা হতো।\n• দামোদর নদ ঝাড়খণ্ডের ছোটনাগপুর মালভূমির পালামৌ জেলার খামারপাত পাহাড় থেকে উৎপন্ন হয়ে রূপনারায়ণ নদীর কাছে ভাগীরথী-হুগলি নদীতে মিলিত হয়েছে।\n• বন্যা নিয়ন্ত্রণের জন্য ১৯৪৮ সালের ৭ই জুলাই স্বাধীন ভারতের প্রথম বহুমুখী নদী উপত্যকা পরিকল্পনা হিসেবে দামোদর ভ্যালি কর্পোরেশন (DVC) গঠিত হয়।\n• আমেরিকার টেনেসি ভ্যালি অথরিটি (TVA)-এর আদলে ডিভিসি প্রকল্পটি পরিকল্পনা ও নির্মাণ করা হয়েছিল।\n• দামোদর নদের প্রধান উপনদীগুলির মধ্যে বরাকর, কোনার ও বোকারো অন্যতম।',
      explanationBengali:
        '• অতীতে বর্ষাকালে দামোদর নদের বিধ্বংসী বন্যায় বর্ধমান ও হুগলির বিস্তীর্ণ অঞ্চল প্লাবিত হতো বলে একে বাংলার দুঃখ (Sorrow of Bengal) বলা হতো।\n• দামোদর নদ ঝাড়খণ্ডের ছোটনাগপুর মালভূমির পালামৌ জেলার খামারপাত পাহাড় থেকে উৎপন্ন হয়ে রূপনারায়ণ নদীর কাছে ভাগীরথী-হুগলি নদীতে মিলিত হয়েছে।\n• বন্যা নিয়ন্ত্রণের জন্য ১৯৪৮ সালের ৭ই জুলাই স্বাধীন ভারতের প্রথম বহুমুখী নদী উপত্যকা পরিকল্পনা হিসেবে দামোদর ভ্যালি কর্পোরেশন (DVC) গঠিত হয়।\n• আমেরিকার টেনেসি ভ্যালি অথরিটি (TVA)-এর আদলে ডিভিসি প্রকল্পটি পরিকল্পনা ও নির্মাণ করা হয়েছিল।\n• দামোদর নদের প্রধান উপনদীগুলির মধ্যে বরাকর, কোনার ও বোকারো অন্যতম।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'pyq',
      sourceExam: 'wbp-constable',
      sourceYear: 2024,
      sourcePaper: 'WBP Preliminary Question Paper 2024',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-pyq-02',
      subjectId: 'wbp-polity',
      subjectName: 'General Awareness',
      chapterName: 'Geography of West Bengal',
      questionText: 'পশ্চিমবঙ্গের বর্তমান সর্বোচ্চ পর্বতশৃঙ্গ কোনটি?',
      questionBengaliText: 'পশ্চিমবঙ্গের বর্তমান সর্বোচ্চ পর্বতশৃঙ্গ কোনটি?',
      optionA: 'সান্দাকফু',
      optionB: 'ফালুট',
      optionC: 'সবরগ্রাম',
      optionD: 'টাইগার হিল',
      correctOption: 'A',
      explanation:
        '• সান্দাকফু (উচ্চতা ৩,৬৩৬ মিটার বা ১১,৯৩০ ফুট) হলো পশ্চিমবঙ্গ তথা সিঙ্গালীলা পর্বতশ্রেণীর সর্বোচ্চ শৃঙ্গ।\n• এটি পশ্চিমবঙ্গ ও নেপালের আন্তর্জাতিক সীমানায় অবস্থিত এবং দার্জিলিং হিমালয়ের অংশ।\n• সান্দাকফুর শৃঙ্গ থেকে বিশ্বের পাঁচটি সর্বোচ্চ পর্বতশৃঙ্গের মধ্যে চারটি (মাউন্ট এভারেস্ট, কাঞ্চনজঙ্ঘা, লোৎসে ও মাকালু) সুস্পষ্টভাবে দেখা যায়।\n• সান্দাকফু শব্দের স্থানীয় উপজাতীয় অর্থ হলো বিষাক্ত উদ্ভিদের চূড়া (Peak of Poison Plants)।\n• পশ্চিমবঙ্গের অন্যান্য উল্লেখযোগ্য শৃঙ্গগুলির মধ্যে রয়েছে ফালুট (৩,৫৯৫ মি.), সবরগ্রাম (৩,৫৪৩ মি.) এবং টাইগার হিল (২,৫৮৪ মি.)।',
      explanationBengali:
        '• সান্দাকফু (উচ্চতা ৩,৬৩৬ মিটার বা ১১,৯৩০ ফুট) হলো পশ্চিমবঙ্গ তথা সিঙ্গালীলা পর্বতশ্রেণীর সর্বোচ্চ শৃঙ্গ।\n• এটি পশ্চিমবঙ্গ ও নেপালের আন্তর্জাতিক সীমানায় অবস্থিত এবং দার্জিলিং হিমালয়ের অংশ।\n• সান্দাকফুর শৃঙ্গ থেকে বিশ্বের পাঁচটি সর্বোচ্চ পর্বতশৃঙ্গের মধ্যে চারটি (মাউন্ট এভারেস্ট, কাঞ্চনজঙ্ঘা, লোৎসে ও মাকালু) সুস্পষ্টভাবে দেখা যায়।\n• সান্দাকফু শব্দের স্থানীয় উপজাতীয় অর্থ হলো বিষাক্ত উদ্ভিদের চূড়া (Peak of Poison Plants)।\n• পশ্চিমবঙ্গের অন্যান্য উল্লেখযোগ্য শৃঙ্গগুলির মধ্যে রয়েছে ফালুট (৩,৫৯৫ মি.), সবরগ্রাম (৩,৫৪৩ মি.) এবং টাইগার হিল (২,৫৮৪ মি.)।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'pyq',
      sourceExam: 'wbp-constable',
      sourceYear: 2024,
      sourcePaper: 'WBP Preliminary Question Paper 2024',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-pyq-03',
      subjectId: 'wbp-history',
      subjectName: 'General Awareness',
      chapterName: 'Modern Indian History & Polity',
      questionText: 'স্বাধীন ভারতে প্রথম সাধারণ নির্বাচন কোন সালে অনুষ্ঠিত হয়েছিল?',
      questionBengaliText: 'স্বাধীন ভারতে প্রথম সাধারণ নির্বাচন কোন সালে অনুষ্ঠিত হয়েছিল?',
      optionA: '১৯৪৭-৪৮ সালে',
      optionB: '১৯৫০-৫১ সালে',
      optionC: '১৯৫১-৫২ সালে',
      optionD: '১৯৫৫-৫৬ সালে',
      correctOption: 'C',
      explanation:
        '• স্বাধীন ভারতে প্রথম লোকসভা সাধারণ নির্বাচন ১৯৫১ সালের ২৫শে অক্টোবর থেকে ১৯৫২ সালের ২১শে ফেব্রুয়ারি পর্যন্ত অনুষ্ঠিত হয়।\n• এই ঐতিহাসিক নির্বাচনে ভারতীয় জাতীয় কংগ্রেস সংখ্যাগরিষ্ঠতা অর্জন করে এবং জওহরলাল নেহরু স্বাধীন ভারতের প্রথম নির্বাচিত প্রধানমন্ত্রী হন।\n• স্বাধীন ভারতের প্রথম মুখ্য নির্বাচন কমিশনার (Chief Election Commissioner) ছিলেন সুকুমার সেন।\n• এই নির্বাচনে ভারতের সমগ্র প্রাপ্তবয়স্ক নাগরিক সর্বজনীন প্রাপ্তবয়স্ক ভোটাধিকার প্রয়োগ করেছিলেন।\n• হিমাচল প্রদেশের চিন্নি গ্রামের বাসিন্দা শ্যাম শরণ নেগি ছিলেন স্বাধীন ভারতের প্রথম ভোটার যিনি ভোট দিয়েছিলেন।',
      explanationBengali:
        '• স্বাধীন ভারতে প্রথম লোকসভা সাধারণ নির্বাচন ১৯৫১ সালের ২৫শে অক্টোবর থেকে ১৯৫২ সালের ২১শে ফেব্রুয়ারি পর্যন্ত অনুষ্ঠিত হয়।\n• এই ঐতিহাসিক নির্বাচনে ভারতীয় জাতীয় কংগ্রেস সংখ্যাগরিষ্ঠতা অর্জন করে এবং জওহরলাল নেহরু স্বাধীন ভারতের প্রথম নির্বাচিত প্রধানমন্ত্রী হন।\n• স্বাধীন ভারতের প্রথম মুখ্য নির্বাচন কমিশনার (Chief Election Commissioner) ছিলেন সুকুমার সেন।\n• এই নির্বাচনে ভারতের সমগ্র প্রাপ্তবয়স্ক নাগরিক সর্বজনীন প্রাপ্তবয়স্ক ভোটাধিকার প্রয়োগ করেছিলেন।\n• হিমাচল প্রদেশের চিন্নি গ্রামের বাসিন্দা শ্যাম শরণ নেগি ছিলেন স্বাধীন ভারতের প্রথম ভোটার যিনি ভোট দিয়েছিলেন।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'pyq',
      sourceExam: 'wbp-constable',
      sourceYear: 2024,
      sourcePaper: 'WBP Preliminary Question Paper 2024',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-wbp-pyq-04',
      subjectId: 'wbp-science',
      subjectName: 'General Awareness',
      chapterName: 'Physical Geography & Atmosphere',
      questionText:
        'বায়ুমণ্ডলের কোন স্তরে মেঘ, বৃষ্টি, কুয়াশা ইত্যাদি যাবতীয় আবহাওয়ার ঘটনা ঘটে?',
      questionBengaliText:
        'বায়ুমণ্ডলের কোন স্তরে মেঘ, বৃষ্টি, কুয়াশা ইত্যাদি যাবতীয় আবহাওয়ার ঘটনা ঘটে?',
      optionA: 'ট্রপোস্ফিয়ার',
      optionB: 'স্ট্র্যাটোস্ফিয়ার',
      optionC: 'মেসোস্ফিয়ার',
      optionD: 'থার্মোস্ফিয়ার',
      correctOption: 'A',
      explanation:
        '• ট্রপোস্ফিয়ার (Troposphere) হলো ভূপৃষ্ঠের সবচেয়ে নিকটবর্তী বায়ুমণ্ডলীয় স্তর, যেখানে মেঘ, বৃষ্টি, ঝড়, কুয়াশা ইত্যাদি আবহাওয়া সংক্রান্ত ঘটনা ঘটে।\n• যাবতীয় আবহাওয়ার অশান্তি ও গোলযোগের কারণে ট্রপোস্ফিয়ারকে ক্ষুব্ধমণ্ডল নামেও ডাকা হয়।\n• এই স্তরে প্রতি ১,০০০ মিটার উচ্চতা বৃদ্ধির সাথে সাথে তাপমাত্রা প্রায় ৬.৪° সেলসিয়াস হারে হ্রাস পায় (Normal Lapse Rate)।\n• বায়ুমণ্ডলের দ্বিতীয় স্তর স্ট্র্যাটোস্ফিয়ারে ওজোন গ্যাসের স্তর থাকে এবং ঝড়-বৃষ্টি না থাকায় এই শান্তমণ্ডল দিয়ে জেট বিমান চলাচল করে।\n• ট্রপোস্ফিয়ারের ঊর্ধ্বসীমায় যেখানে তাপমাত্রা হ্রাস পাওয়া বন্ধ হয় তাকে ট্রপোপজ (Tropopause) বলা হয়।',
      explanationBengali:
        '• ট্রপোস্ফিয়ার (Troposphere) হলো ভূপৃষ্ঠের সবচেয়ে নিকটবর্তী বায়ুমণ্ডলীয় স্তর, যেখানে মেঘ, বৃষ্টি, ঝড়, কুয়াশা ইত্যাদি আবহাওয়া সংক্রান্ত ঘটনা ঘটে।\n• যাবতীয় আবহাওয়ার অশান্তি ও গোলযোগের কারণে ট্রপোস্ফিয়ারকে ক্ষুব্ধমণ্ডল নামেও ডাকা হয়।\n• এই স্তরে প্রতি ১,০০০ মিটার উচ্চতা বৃদ্ধির সাথে সাথে তাপমাত্রা প্রায় ৬.৪° সেলসিয়াস হারে হ্রাস পায় (Normal Lapse Rate)।\n• বায়ুমণ্ডলের দ্বিতীয় স্তর স্ট্র্যাটোস্ফিয়ারে ওজোন গ্যাসের স্তর থাকে এবং ঝড়-বৃষ্টি না থাকায় এই শান্তমণ্ডল দিয়ে জেট বিমান চলাচল করে।\n• ট্রপোস্ফিয়ারের ঊর্ধ্বসীমায় যেখানে তাপমাত্রা হ্রাস পাওয়া বন্ধ হয় তাকে ট্রপোপজ (Tropopause) বলা হয়।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'pyq',
      sourceExam: 'wbp-constable',
      sourceYear: 2024,
      sourcePaper: 'WBP Preliminary Question Paper 2024',
      isActive: true,
      status: 'active',
    },
  ],
  'topic-math-ratio': [
    {
      id: 'q-math-ratio-01',
      subjectId: 'wbp-math',
      chapterId: 'wbp-math-ratio',
      topicId: 'wbp-math-ratio',
      questionText: 'A এবং B এর বয়সের অনুপাত 4:5 এবং তাদের বয়সের সমষ্টি 36 বছর হলে B এর বয়স কত?',
      questionBengaliText:
        'A এবং B এর বয়সের অনুপাত 4:5 এবং তাদের বয়সের সমষ্টি 36 বছর হলে B এর বয়স কত?',
      optionA: '16 বছর',
      optionB: '20 বছর',
      optionC: '24 বছর',
      optionD: '18 বছর',
      correctOption: 'B',
      explanation:
        '• অনুপাতের মোট আনুপাতিক সমষ্টি বা ভাগহার = 4 + 5 = 9 ভাগ।\n• প্রশ্নানুসারে মোট ৯ ভাগ = 36 বছর, সুতরাং ১ ভাগের মান = 36 ÷ 9 = 4 বছর।\n• অতএব B এর বয়স = 5 × 4 = 20 বছর এবং A এর বয়স = 4 × 4 = 16 বছর।\n• সত্যতা যাচাই: 16 + 20 = 36 বছর এবং 16:20 = 4:5, যা প্রশ্নের শর্তের সাথে সম্পূর্ণ মিলে যায়।\n• সরাসরি শর্টকাট সূত্র: নির্দিষ্ট অংশ = (অনুপাত পদ ÷ মোট অনুপাত) × মোট রাশি = (5/9) × 36 = 20 বছর।',
      explanationBengali:
        '• অনুপাতের মোট আনুপাতিক সমষ্টি বা ভাগহার = 4 + 5 = 9 ভাগ।\n• প্রশ্নানুসারে মোট ৯ ভাগ = 36 বছর, সুতরাং ১ ভাগের মান = 36 ÷ 9 = 4 বছর।\n• অতএব B এর বয়স = 5 × 4 = 20 বছর এবং A এর বয়স = 4 × 4 = 16 বছর।\n• সত্যতা যাচাই: 16 + 20 = 36 বছর এবং 16:20 = 4:5, যা প্রশ্নের শর্তের সাথে সম্পূর্ণ মিলে যায়।\n• সরাসরি শর্টকাট সূত্র: নির্দিষ্ট অংশ = (অনুপাত পদ ÷ মোট অনুপাত) × মোট রাশি = (5/9) × 36 = 20 বছর।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
    {
      id: 'q-math-ratio-02',
      subjectId: 'wbp-math',
      chapterId: 'wbp-math-ratio',
      topicId: 'wbp-math-ratio',
      questionText: 'যদি A : B = 2 : 3 এবং B : C = 4 : 5 হয়, তবে A : C এর মান কত?',
      questionBengaliText: 'যদি A : B = 2 : 3 এবং B : C = 4 : 5 হয়, তবে A : C এর মান কত?',
      optionA: '8 : 15',
      optionB: '6 : 15',
      optionC: '2 : 5',
      optionD: '15 : 8',
      correctOption: 'A',
      explanation:
        '• অনুপাতগুলিকে ভগ্নাংশে প্রকাশ করে পাই: A/B = 2/3 এবং B/C = 4/5।\n• প্রান্তিক অনুপাত নির্ণয়ের সূত্র: A/C = (A/B) × (B/C)।\n• মান বসিয়ে পাই: A/C = (2/3) × (4/5) = (2 × 4) / (3 × 5) = 8/15।\n• অতএব নির্ণেয় যৌগিক অনুপাত A : C = 8 : 15।\n• সম্পূর্ণ সংযুক্ত অনুপাত A:B:C বের করার শর্টকাট নিয়ম: A:B:C = (2×4) : (3×4) : (3×5) = 8 : 12 : 15।',
      explanationBengali:
        '• অনুপাতগুলিকে ভগ্নাংশে প্রকাশ করে পাই: A/B = 2/3 এবং B/C = 4/5।\n• প্রান্তিক অনুপাত নির্ণয়ের সূত্র: A/C = (A/B) × (B/C)।\n• মান বসিয়ে পাই: A/C = (2/3) × (4/5) = (2 × 4) / (3 × 5) = 8/15।\n• অতএব নির্ণেয় যৌগিক অনুপাত A : C = 8 : 15।\n• সম্পূর্ণ সংযুক্ত অনুপাত A:B:C বের করার শর্টকাট নিয়ম: A:B:C = (2×4) : (3×4) : (3×5) = 8 : 12 : 15।',
      difficulty: 'medium',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
  'topic-math-percentage': [
    {
      id: 'q-math-perc-01',
      subjectId: 'wbp-math',
      chapterId: 'wbp-math-percentage',
      topicId: 'wbp-math-percentage',
      questionText:
        'একটি বইয়ের ধার্যমূল্য 120 টাকা। বইটি 10% ছাড়ে বিক্রি করা হলে বিক্রয়মূল্য কত?',
      questionBengaliText:
        'একটি বইয়ের ধার্যমূল্য 120 টাকা। বইটি 10% ছাড়ে বিক্রি করা হলে বিক্রয়মূল্য কত?',
      optionA: '100 টাকা',
      optionB: '108 টাকা',
      optionC: '110 টাকা',
      optionD: '112 টাকা',
      correctOption: 'B',
      explanation:
        '• বইটির ধার্যমূল্য (Marked Price) = 120 টাকা এবং প্রদত্ত ছাড়ের হার (Discount) = 10%।\n• মোট ছাড়ের পরিমাণ = 120 × (10/100) = 12 টাকা।\n• বিক্রয়মূল্য (Selling Price) = ধার্যমূল্য - ছাড় = 120 - 12 = 108 টাকা।\n• সরাসরি শতকরা সূত্রের শর্টকাট: বিক্রয়মূল্য = 120 × (100 - 10)% = 120 × 0.90 = 108 টাকা।\n• মনে রাখবেন শতকরা ছাড় সর্বদা পণ্যের ধার্যমূল্য বা এমআরপি-র ওপর হিসাব করতে হয়।',
      explanationBengali:
        '• বইটির ধার্যমূল্য (Marked Price) = 120 টাকা এবং প্রদত্ত ছাড়ের হার (Discount) = 10%।\n• মোট ছাড়ের পরিমাণ = 120 × (10/100) = 12 টাকা।\n• বিক্রয়মূল্য (Selling Price) = ধার্যমূল্য - ছাড় = 120 - 12 = 108 টাকা।\n• সরাসরি শতকরা সূত্রের শর্টকাট: বিক্রয়মূল্য = 120 × (100 - 10)% = 120 × 0.90 = 108 টাকা।\n• মনে রাখবেন শতকরা ছাড় সর্বদা পণ্যের ধার্যমূল্য বা এমআরপি-র ওপর হিসাব করতে হয়।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
  'topic-sci-physics': [
    {
      id: 'q-sci-phys-01',
      subjectId: 'wbp-science',
      chapterId: 'wbp-sci-physics',
      topicId: 'wbp-sci-physics',
      questionText: 'SI পদ্ধতিতে বলের (Force) একক কী?',
      questionBengaliText: 'SI পদ্ধতিতে বলের (Force) একক কী?',
      optionA: 'ডাইন',
      optionB: 'নিউটন',
      optionC: 'জুল',
      optionD: 'ওয়াট',
      correctOption: 'B',
      explanation:
        '• আন্তর্জাতিক এসআই (SI) পদ্ধতিতে বলের পরম একক হলো নিউটন (Newton), সংক্ষেপে N দ্বারা প্রকাশ করা হয়।\n• বলের সমীকরণ: বল (F) = ভর (m) × ত্বরণ (a), অর্থাৎ ১ নিউটন = ১ কেজি × ১ মিটার/সেকেন্ড² (1 N = 1 kg·m/s²)।\n• সিজিএস (CGS) পদ্ধতিতে বলের পরম একক হলো ডাইন (Dyne)।\n• নিউটন ও ডাইনের মধ্যে পারস্পরিক সম্পর্ক: ১ নিউটন = ১০⁵ ডাইন (1 N = 100,000 Dynes)।\n• কাজের বা শক্তির এসআই একক হলো জুল (Joule) এবং ক্ষমতার এসআই একক হলো ওয়াট (Watt)।',
      explanationBengali:
        '• আন্তর্জাতিক এসআই (SI) পদ্ধতিতে বলের পরম একক হলো নিউটন (Newton), সংক্ষেপে N দ্বারা প্রকাশ করা হয়।\n• বলের সমীকরণ: বল (F) = ভর (m) × ত্বরণ (a), অর্থাৎ ১ নিউটন = ১ কেজি × ১ মিটার/সেকেন্ড² (1 N = 1 kg·m/s²)।\n• সিজিএস (CGS) পদ্ধতিতে বলের পরম একক হলো ডাইন (Dyne)।\n• নিউটন ও ডাইনের মধ্যে পারস্পরিক সম্পর্ক: ১ নিউটন = ১০⁵ ডাইন (1 N = 100,000 Dynes)।\n• কাজের বা শক্তির এসআই একক হলো জুল (Joule) এবং ক্ষমতার এসআই একক হলো ওয়াট (Watt)।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
  'topic-pol-rights': [
    {
      id: 'q-pol-rights-01',
      subjectId: 'wbp-polity',
      chapterId: 'wbp-pol-rights',
      topicId: 'wbp-pol-rights',
      questionText: 'ভারতীয় সংবিধানের কত নম্বর ধারায় অস্পৃশ্যতা দূরীকরণের কথা বলা হয়েছে?',
      questionBengaliText: 'ভারতীয় সংবিধানের কত নম্বর ধারায় অস্পৃশ্যতা দূরীকরণের কথা বলা হয়েছে?',
      optionA: 'ধারা 14',
      optionB: 'ধারা 17',
      optionC: 'ধারা 19',
      optionD: 'ধারা 21',
      correctOption: 'B',
      explanation:
        '• ভারতীয় সংবিধানের তৃতীয় অংশে (Part III) অনুচ্ছেদ ১৭-তে অস্পৃশ্যতা বিলোপ (Abolition of Untouchability) নিশ্চিত করা হয়েছে।\n• অনুচ্ছেদ ১৭ হলো একটি পরম অধিকার (Absolute Right), যার কোনো ব্যতিক্রম বা সীমাবদ্ধতা সংবিধানে নেই।\n• অস্পৃশ্যতা দূরীকরণকে আইনত দণ্ডনীয় অপরাধ করতে ১৯৫৫ সালে সংসদ Untouchability (Offences) Act পাস করে, যা বর্তমানে Protection of Civil Rights Act নামে পরিচিত।\n• সংবিধানের ১৪ থেকে ১৮ নম্বর অনুচ্ছেদ পর্যন্ত সাম্যের অধিকার (Right to Equality) বিস্তারিত ব্যাখ্যা করা হয়েছে।\n• ধারা ১৪ আইনের দৃষ্টিতে সমতা, ধারা ১৫ বৈষম্যহীনতা, ধারা ১৬ সরকারি চাকুরিতে সমসুযোগ এবং ধারা ১৮ খেতাব বিলোপ নিশ্চিত করে।',
      explanationBengali:
        '• ভারতীয় সংবিধানের তৃতীয় অংশে (Part III) অনুচ্ছেদ ১৭-তে অস্পৃশ্যতা বিলোপ (Abolition of Untouchability) নিশ্চিত করা হয়েছে।\n• অনুচ্ছেদ ১৭ হলো একটি পরম অধিকার (Absolute Right), যার কোনো ব্যতিক্রম বা সীমাবদ্ধতা সংবিধানে নেই।\n• অস্পৃশ্যতা দূরীকরণকে আইনত দণ্ডনীয় অপরাধ করতে ১৯৫৫ সালে সংসদ Untouchability (Offences) Act পাস করে, যা বর্তমানে Protection of Civil Rights Act নামে পরিচিত।\n• সংবিধানের ১৪ থেকে ১৮ নম্বর অনুচ্ছেদ পর্যন্ত সাম্যের অধিকার (Right to Equality) বিস্তারিত ব্যাখ্যা করা হয়েছে।\n• ধারা ১৪ আইনের দৃষ্টিতে সমতা, ধারা ১৫ বৈষম্যহীনতা, ধারা ১৬ সরকারি চাকুরিতে সমসুযোগ এবং ধারা ১৮ খেতাব বিলোপ নিশ্চিত করে।',
      difficulty: 'easy',
      defaultMarks: 1.0,
      defaultNegativeMarks: 0,
      sourceType: 'topic',
      isActive: true,
      status: 'active',
    },
  ],
};

export const MOCK_ATTEMPTS: TestAttempt[] = [
  {
    id: 'att-001',
    userId: 'usr-student-001',
    testId: 'test-indus-01',
    testTitle: 'Mock Test Part 01: Indus Valley (Free)',
    status: 'completed',
    startTime: '2025-02-10T14:00:00Z',
    endTime: '2025-02-10T14:11:30Z',
    timeSpentSeconds: 690,
    score: 4.75,
    totalMarks: 5.0,
    correctCount: 4,
    wrongCount: 1,
    skippedCount: 0,
    accuracy: 80.0,
    rank: 14,
    percentile: 94.5,
    createdAt: '2025-02-10T14:12:00Z',
  },
];

export const MOCK_MISTAKES: MistakeItem[] = [
  {
    id: 'mst-001',
    userId: 'usr-student-001',
    questionId: 'q-indus-05',
    question: MOCK_QUESTIONS['test-indus-01'][4],
    wrongCount: 2,
    isResolved: false,
    lastReviewedAt: '2025-02-10T14:15:00Z',
    createdAt: '2025-02-10T14:12:00Z',
  },
];

export const MOCK_BOOKMARKS: BookmarkItem[] = [
  {
    id: 'bm-001',
    userId: 'usr-student-001',
    questionId: 'q-bm-gk-01',
    examTitle: 'WBP Constable',
    subjectName: 'General Knowledge',
    chapterName: 'Important Firsts',
    createdAt: '2026-09-12T10:30:00Z',
    question: {
      id: 'q-bm-gk-01',
      questionText: 'Who was the first woman to win a Nobel Prize?',
      optionA: 'Marie Curie',
      optionB: 'Mother Teresa',
      optionC: 'Indira Gandhi',
      optionD: 'Kalpana Chawla',
      correctOption: 'A',
      explanation: 'Marie Curie was the first woman to win a Nobel Prize (Physics in 1903) and the first person to win Nobel Prizes in two different scientific fields (Physics and Chemistry in 1911).',
      difficulty: 'medium',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'General Knowledge',
    },
  },
  {
    id: 'bm-002',
    userId: 'usr-student-001',
    questionId: 'q-bm-math-01',
    examTitle: 'SSC GD',
    subjectName: 'Mathematics',
    chapterName: 'Geometry & Mensuration',
    createdAt: '2026-09-10T09:15:00Z',
    question: {
      id: 'q-bm-math-01',
      questionText: 'If the sum of interior angles of a polygon is 1440°, then the number of sides is:',
      optionA: '8',
      optionB: '9',
      optionC: '10',
      optionD: '12',
      correctOption: 'C',
      explanation: 'Sum of interior angles = (n - 2) * 180° = 1440° => n - 2 = 1440 / 180 = 8 => n = 10 sides.',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Mathematics',
    },
  },
  {
    id: 'bm-003',
    userId: 'usr-student-001',
    questionId: 'q-bm-reas-01',
    examTitle: 'WBP Constable',
    subjectName: 'Reasoning',
    chapterName: 'Classification / Odd One Out',
    createdAt: '2026-09-08T14:20:00Z',
    question: {
      id: 'q-bm-reas-01',
      questionText: 'Find the odd one out:',
      optionA: 'Apple',
      optionB: 'Orange',
      optionC: 'Carrot',
      optionD: 'Banana',
      correctOption: 'C',
      explanation: 'Carrot is a root vegetable that grows underground, whereas Apple, Orange, and Banana are fruits that grow on trees/plants.',
      difficulty: 'medium',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Reasoning',
    },
  },
  {
    id: 'bm-004',
    userId: 'usr-student-001',
    questionId: 'q-bm-ben-01',
    examTitle: 'Primary TET',
    subjectName: 'Bengali',
    chapterName: 'শব্দার্থ ও সমার্থক শব্দ',
    createdAt: '2026-09-05T11:45:00Z',
    question: {
      id: 'q-bm-ben-01',
      questionText: '"আকাশ" শব্দের অর্থ কী?',
      optionA: 'গগন / অম্বর',
      optionB: 'মেঘ',
      optionC: 'বাতাস',
      optionD: 'তারা',
      correctOption: 'A',
      explanation: 'আকাশ শব্দের সমার্থক ও প্রচলিত অর্থ হলো গগন, অম্বর, ব্যোম বা নভোমণ্ডল।',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Bengali',
    },
  },
  {
    id: 'bm-005',
    userId: 'usr-student-001',
    questionId: 'q-bm-eng-01',
    examTitle: 'WBSSC',
    subjectName: 'English',
    chapterName: 'Subject-Verb Agreement',
    createdAt: '2026-09-01T16:00:00Z',
    question: {
      id: 'q-bm-eng-01',
      questionText: 'Choose the correct form: She ___ to school every day.',
      optionA: 'go',
      optionB: 'goes',
      optionC: 'going',
      optionD: 'gone',
      correctOption: 'B',
      explanation: 'For third-person singular subjects (he, she, it) in simple present tense representing a daily routine, the verb takes "s" or "es" (goes).',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'English',
    },
  },
  {
    id: 'bm-006',
    userId: 'usr-student-001',
    questionId: 'q-bm-gk-02',
    examTitle: 'WBPSC Clerkship',
    subjectName: 'General Knowledge',
    chapterName: 'Ancient Indian History',
    createdAt: '2026-08-28T12:00:00Z',
    question: {
      id: 'q-bm-gk-02',
      questionText: 'In which Indian state is the ancient Harappan port city of Lothal situated?',
      optionA: 'Rajasthan',
      optionB: 'Gujarat',
      optionC: 'Punjab',
      optionD: 'Haryana',
      correctOption: 'B',
      explanation: 'Lothal is located near the village of Saragwala in the Dholka Taluka of Ahmedabad district, Gujarat.',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'General Knowledge',
    },
  },
  {
    id: 'bm-007',
    userId: 'usr-student-001',
    questionId: 'q-bm-gk-03',
    examTitle: 'KP SI',
    subjectName: 'General Knowledge',
    chapterName: 'Indian Polity & Constitution',
    createdAt: '2026-08-25T15:30:00Z',
    question: {
      id: 'q-bm-gk-03',
      questionText: 'Which Articles of the Indian Constitution deal with the Right to Equality?',
      optionA: 'Articles 14 to 18',
      optionB: 'Articles 19 to 22',
      optionC: 'Articles 23 to 24',
      optionD: 'Articles 25 to 28',
      correctOption: 'A',
      explanation: 'Articles 14-18 of the Indian Constitution guarantee the fundamental Right to Equality for all citizens.',
      difficulty: 'medium',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'General Knowledge',
    },
  },
  {
    id: 'bm-008',
    userId: 'usr-student-001',
    questionId: 'q-bm-gk-04',
    examTitle: 'WBCS Prelims',
    subjectName: 'General Knowledge',
    chapterName: 'Social Reforms & History',
    createdAt: '2026-08-20T10:00:00Z',
    question: {
      id: 'q-bm-gk-04',
      questionText: 'Who founded the social reform organisation "Satya Shodhak Samaj" in 1873?',
      optionA: 'Swami Vivekananda',
      optionB: 'Jyotirao Phule',
      optionC: 'Raja Ram Mohan Roy',
      optionD: 'Ishwar Chandra Vidyasagar',
      correctOption: 'B',
      explanation: 'Mahatma Jyotirao Phule founded the Satyashodhak Samaj in Pune in 1873 to liberate lower caste people from social exploitation.',
      difficulty: 'hard',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'General Knowledge',
    },
  },
  {
    id: 'bm-009',
    userId: 'usr-student-001',
    questionId: 'q-bm-gk-05',
    examTitle: 'Railway NTPC',
    subjectName: 'General Knowledge',
    chapterName: 'Geography of West Bengal',
    createdAt: '2026-08-18T14:00:00Z',
    question: {
      id: 'q-bm-gk-05',
      questionText: 'Which river was historically known as the "Sorrow of Bengal"?',
      optionA: 'Hooghly River',
      optionB: 'Damodar River',
      optionC: 'Teesta River',
      optionD: 'Rupnarayan River',
      correctOption: 'B',
      explanation: 'The Damodar River was formerly known as the Sorrow of Bengal because of its frequent devastating floods before the construction of DVC dams.',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'General Knowledge',
    },
  },
  {
    id: 'bm-010',
    userId: 'usr-student-001',
    questionId: 'q-bm-gk-06',
    examTitle: 'WBP Lady Constable',
    subjectName: 'General Knowledge',
    chapterName: 'General Science',
    createdAt: '2026-08-15T09:00:00Z',
    question: {
      id: 'q-bm-gk-06',
      questionText: 'What is the standard chemical Latin symbol for Gold?',
      optionA: 'Ag',
      optionB: 'Au',
      optionC: 'Fe',
      optionD: 'Pb',
      correctOption: 'B',
      explanation: 'The chemical symbol Au comes from the Latin word "Aurum", which means shining dawn or gold.',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'General Knowledge',
    },
  },
  {
    id: 'bm-011',
    userId: 'usr-student-001',
    questionId: 'q-bm-gk-07',
    examTitle: 'WB Food SI',
    subjectName: 'General Knowledge',
    chapterName: 'Everyday Science',
    createdAt: '2026-08-12T11:20:00Z',
    question: {
      id: 'q-bm-gk-07',
      questionText: 'What are the main gaseous constituents of domestic LPG cylinders?',
      optionA: 'Methane and Ethane',
      optionB: 'Butane and Propane',
      optionC: 'Carbon Monoxide and Hydrogen',
      optionD: 'Nitrogen and Carbon Dioxide',
      correctOption: 'B',
      explanation: 'Domestic liquefied petroleum gas (LPG) predominantly consists of propane and butane hydrocarbon gases.',
      difficulty: 'medium',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'General Knowledge',
    },
  },
  {
    id: 'bm-012',
    userId: 'usr-student-001',
    questionId: 'q-bm-gk-08',
    examTitle: 'KP Constable',
    subjectName: 'General Knowledge',
    chapterName: 'Indian National Movement',
    createdAt: '2026-08-10T16:45:00Z',
    question: {
      id: 'q-bm-gk-08',
      questionText: 'Who composed the national song of India "Vande Mataram"?',
      optionA: 'Rabindranath Tagore',
      optionB: 'Bankim Chandra Chattopadhyay',
      optionC: 'Kazi Nazrul Islam',
      optionD: 'Dwijendralal Ray',
      correctOption: 'B',
      explanation: 'Vande Mataram was written by Bankim Chandra Chattopadhyay in his 1882 novel Anandamath.',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'General Knowledge',
    },
  },
  {
    id: 'bm-013',
    userId: 'usr-student-001',
    questionId: 'q-bm-math-02',
    examTitle: 'WBP SI',
    subjectName: 'Mathematics',
    chapterName: 'Speed, Time and Distance',
    createdAt: '2026-08-08T13:10:00Z',
    question: {
      id: 'q-bm-math-02',
      questionText: 'A train 150m long is running at 54 km/h. How many seconds will it take to cross a telegraph post?',
      optionA: '10 seconds',
      optionB: '12 seconds',
      optionC: '15 seconds',
      optionD: '18 seconds',
      correctOption: 'A',
      explanation: 'Speed = 54 * (5/18) = 15 m/s. Time to cross post = Distance / Speed = 150 / 15 = 10 seconds.',
      difficulty: 'medium',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Mathematics',
    },
  },
  {
    id: 'bm-014',
    userId: 'usr-student-001',
    questionId: 'q-bm-math-03',
    examTitle: 'WBPSC Clerkship',
    subjectName: 'Mathematics',
    chapterName: 'Simple Interest',
    createdAt: '2026-08-05T10:30:00Z',
    question: {
      id: 'q-bm-math-03',
      questionText: 'If the simple interest on a sum of money for 3 years at 5% per annum is ₹150, what is the principal?',
      optionA: '₹800',
      optionB: '₹1000',
      optionC: '₹1200',
      optionD: '₹1500',
      correctOption: 'B',
      explanation: 'Principal P = (SI * 100) / (R * T) = (150 * 100) / (5 * 3) = 15000 / 15 = ₹1000.',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Mathematics',
    },
  },
  {
    id: 'bm-015',
    userId: 'usr-student-001',
    questionId: 'q-bm-math-04',
    examTitle: 'SSC MTS',
    subjectName: 'Mathematics',
    chapterName: 'LCM and HCF',
    createdAt: '2026-08-02T15:20:00Z',
    question: {
      id: 'q-bm-math-04',
      questionText: 'The ratio of two numbers is 3:4 and their HCF is 4. What is their LCM?',
      optionA: '12',
      optionB: '16',
      optionC: '24',
      optionD: '48',
      correctOption: 'D',
      explanation: 'The numbers are 3*4 = 12 and 4*4 = 16. LCM of 12 and 16 is 48.',
      difficulty: 'medium',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Mathematics',
    },
  },
  {
    id: 'bm-016',
    userId: 'usr-student-001',
    questionId: 'q-bm-math-05',
    examTitle: 'WBP Constable',
    subjectName: 'Mathematics',
    chapterName: 'Percentage',
    createdAt: '2026-07-29T11:00:00Z',
    question: {
      id: 'q-bm-math-05',
      questionText: 'Find the value of x if 25% of x is equal to 80.',
      optionA: '240',
      optionB: '300',
      optionC: '320',
      optionD: '400',
      correctOption: 'C',
      explanation: '0.25 * x = 80 => x = 80 / 0.25 = 320.',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Mathematics',
    },
  },
  {
    id: 'bm-017',
    userId: 'usr-student-001',
    questionId: 'q-bm-reas-02',
    examTitle: 'KP SI',
    subjectName: 'Reasoning',
    chapterName: 'Blood Relations',
    createdAt: '2026-07-25T14:40:00Z',
    question: {
      id: 'q-bm-reas-02',
      questionText: "Pointing to a photograph, a man said: 'He is the son of the only daughter of the father of my brother.' How is the man related to the boy?",
      optionA: 'Brother',
      optionB: 'Maternal Uncle (মামা)',
      optionC: 'Father',
      optionD: 'Grandfather',
      correctOption: 'B',
      explanation: "Father of my brother = my father. The only daughter of my father = my sister. Son of my sister = nephew. Therefore, the man is his maternal uncle (মামা).",
      difficulty: 'hard',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Reasoning',
    },
  },
  {
    id: 'bm-018',
    userId: 'usr-student-001',
    questionId: 'q-bm-reas-03',
    examTitle: 'SSC CGL',
    subjectName: 'Reasoning',
    chapterName: 'Number Series',
    createdAt: '2026-07-22T09:30:00Z',
    question: {
      id: 'q-bm-reas-03',
      questionText: 'Complete the logical number series: 3, 7, 15, 31, 63, ?',
      optionA: '95',
      optionB: '115',
      optionC: '127',
      optionD: '131',
      correctOption: 'C',
      explanation: 'Pattern: (n * 2) + 1. So 63 * 2 + 1 = 126 + 1 = 127.',
      difficulty: 'medium',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Reasoning',
    },
  },
  {
    id: 'bm-019',
    userId: 'usr-student-001',
    questionId: 'q-bm-reas-04',
    examTitle: 'WBP Constable',
    subjectName: 'Reasoning',
    chapterName: 'Coding & Decoding',
    createdAt: '2026-07-18T16:15:00Z',
    question: {
      id: 'q-bm-reas-04',
      questionText: 'If CAT is coded as 3120 (C=3, A=1, T=20), then how will DOG be coded?',
      optionA: '4157',
      optionB: '4147',
      optionC: '3157',
      optionD: '4158',
      correctOption: 'A',
      explanation: 'Alphabetical positions: D = 4, O = 15, G = 7 => 4157.',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Reasoning',
    },
  },
  {
    id: 'bm-020',
    userId: 'usr-student-001',
    questionId: 'q-bm-ben-02',
    examTitle: 'Primary TET',
    subjectName: 'Bengali',
    chapterName: 'সন্ধি বিচ্ছেদ',
    createdAt: '2026-07-15T12:00:00Z',
    question: {
      id: 'q-bm-ben-02',
      questionText: 'সঠিক সন্ধি বিচ্ছেদ কোনটি: "বিদ্যালয়" = ?',
      optionA: 'বিদ্যা + আলয়',
      optionB: 'বিদ + আলয়',
      optionC: 'বিদ্যা + লয়',
      optionD: 'বিদ্য + আলয়',
      correctOption: 'A',
      explanation: 'আ-কার ও আ-কার মিলে আ-কার হয়: বিদ্যা + আলয় = বিদ্যালয়।',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Bengali',
    },
  },
  {
    id: 'bm-021',
    userId: 'usr-student-001',
    questionId: 'q-bm-ben-03',
    examTitle: 'WBPSC Miscellaneous',
    subjectName: 'Bengali',
    chapterName: 'বিপরীত ও সমার্থক শব্দ',
    createdAt: '2026-07-12T10:15:00Z',
    question: {
      id: 'q-bm-ben-03',
      questionText: '"অগ্নি" শব্দের সমার্থক শব্দ কোনটি নয়?',
      optionA: 'অনল',
      optionB: 'পাবক',
      optionC: 'হুতাশন',
      optionD: 'অম্বু',
      correctOption: 'D',
      explanation: 'অনল, পাবক ও হুতাশন হলো অগ্নির প্রতিশব্দ। "অম্বু" শব্দের অর্থ জল বা পানি।',
      difficulty: 'medium',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Bengali',
    },
  },
  {
    id: 'bm-022',
    userId: 'usr-student-001',
    questionId: 'q-bm-ben-04',
    examTitle: 'WBP Constable',
    subjectName: 'Bengali',
    chapterName: 'এক কথায় প্রকাশ',
    createdAt: '2026-07-08T15:00:00Z',
    question: {
      id: 'q-bm-ben-04',
      questionText: '"যার কোনো শত্রু জন্মায়নি" — এক কথায় প্রকাশ কী হবে?',
      optionA: 'শত্রুহীন',
      optionB: 'অজাতশত্রু',
      optionC: 'নিঃশত্রু',
      optionD: 'অরিজিৎ',
      correctOption: 'B',
      explanation: 'যার কোনো শত্রু জন্মায়নি তাকে এক কথায় বলা হয় "অজাতশত্রু"।',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'Bengali',
    },
  },
  {
    id: 'bm-023',
    userId: 'usr-student-001',
    questionId: 'q-bm-eng-02',
    examTitle: 'WBPSC Clerkship',
    subjectName: 'English',
    chapterName: 'Vocabulary & Synonyms',
    createdAt: '2026-07-05T11:30:00Z',
    question: {
      id: 'q-bm-eng-02',
      questionText: 'Identify the exact synonym of the word "MANDATORY":',
      optionA: 'Optional',
      optionB: 'Compulsory',
      optionC: 'Voluntary',
      optionD: 'Flexible',
      correctOption: 'B',
      explanation: 'Mandatory means required by law or rules; compulsory or obligatory.',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'English',
    },
  },
  {
    id: 'bm-024',
    userId: 'usr-student-001',
    questionId: 'q-bm-eng-03',
    examTitle: 'WBP SI',
    subjectName: 'English',
    chapterName: 'Antonyms',
    createdAt: '2026-07-01T14:20:00Z',
    question: {
      id: 'q-bm-eng-03',
      questionText: 'Select the most appropriate antonym of "OPTIMISTIC":',
      optionA: 'Pessimistic',
      optionB: 'Hopeful',
      optionC: 'Positive',
      optionD: 'Cheerful',
      correctOption: 'A',
      explanation: 'Optimistic means hopeful and confident about the future. Its opposite is pessimistic (expecting the worst).',
      difficulty: 'easy',
      defaultMarks: 1,
      defaultNegativeMarks: 0,
      isActive: true,
      subjectName: 'English',
    },
  },
];

export const MOCK_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan_free',
    title: 'Free Plan',
    description:
      'Basic access to free practice content. Topic-wise practice tests and limited mock tests available for all aspirants.',
    durationDays: 36500,
    price: 0,
    originalPrice: 0,
    currency: 'INR',
    features: [
      'Topic-wise Practice Tests (Free)',
      'Limited Free Mock Tests',
      'Basic Performance Summary',
      'Mistakes Notebook (Last 5 Tests)',
      'Full Syllabus Practice Tests',
    ],
    isActive: true,
    orderIndex: 0,
  },
  {
    id: 'pro_1_year',
    title: '1-Year All-Access Pass',
    description:
      'Unlimited access to ALL Premium Mock Tests across all West Bengal exams for 365 days.',
    durationDays: 365,
    price: 299,
    originalPrice: 999,
    currency: 'INR',
    features: [
      'Everything in Free Plan +',
      'Unlock ALL Premium Mock Tests across all exams',
      'WBP Constable, KP SI, WBCS & WBPSC Clerkship',
      'Automatic Mistakes Notebook & Smart Revision',
      'Detailed Step-by-Step Explanations',
      'State-Level Rank & Percentile Analytics',
      'Validity: Full 365 Days',
    ],
    isActive: true,
    orderIndex: 1,
  },
  {
    id: 'pro_6_month',
    title: '6-Month Exam Pass',
    description: 'Complete access to all premium tests for 180 days.',
    durationDays: 180,
    price: 199,
    originalPrice: 599,
    currency: 'INR',
    features: [
      'Everything in Free Plan +',
      'Unlock ALL Premium Mock Tests',
      'Detailed Explanations & Solutions',
      'Mistakes Notebook & Bookmarks',
      'Validity: 180 Days',
    ],
    isActive: true,
    orderIndex: 2,
  },
];
